### ISSUE TITLE
Config interpolation no longer working

### ISSUE THREAD

**Issue by edjames** [fluent/fluent-plugin-s3#109]
Hi

Since upgrading to 0.6.0 I've had to update my config files because the interpolation has suddenly stopped working.

I used to have this:
```
aws_key_id "#{ENV['S3_KEY']}"
aws_sec_key "#{ENV['S3_SECRET']}"
```

These were both set in the `/etc/environment` file and were working perfectly with version 0.5.11. I only upgraded to 0.6.0 and restarted my td-agent service, and then got this log trace:

```
2015-10-13 10:40:24 +0000 [error]: unexpected error error_class=RuntimeError error=#<RuntimeError: can't call S3 API. Please check your aws_key_id / aws_sec_key or s3_region configuration. error = #<Aws::Errors::MissingCredentialsError: unable to sign request without credentials set>>
  2015-10-13 10:40:24 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-s3-0.6.0/lib/fluent/plugin/out_s3.rb:193:in `rescue in check_apikeys'
  2015-10-13 10:40:24 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-s3-0.6.0/lib/fluent/plugin/out_s3.rb:189:in `check_apikeys'
  2015-10-13 10:40:24 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-s3-0.6.0/lib/fluent/plugin/out_s3.rb:112:in `start'
  2015-10-13 10:40:24 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/plugin/out_copy.rb:50:in `block in start'
  2015-10-13 10:40:24 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/plugin/out_copy.rb:49:in `each'
  2015-10-13 10:40:24 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/plugin/out_copy.rb:49:in `start'
  2015-10-13 10:40:24 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/agent.rb:67:in `block in start'
  2015-10-13 10:40:24 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/agent.rb:66:in `each'
  2015-10-13 10:40:24 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/agent.rb:66:in `start'
  2015-10-13 10:40:24 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/root_agent.rb:104:in `start'
  2015-10-13 10:40:24 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/engine.rb:201:in `start'
  2015-10-13 10:40:24 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/engine.rb:151:in `run'
  2015-10-13 10:40:24 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/supervisor.rb:539:in `run_engine'
  2015-10-13 10:40:24 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/supervisor.rb:143:in `block in start'
  2015-10-13 10:40:24 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/supervisor.rb:306:in `call'
  2015-10-13 10:40:24 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/supervisor.rb:306:in `main_process'
  2015-10-13 10:40:24 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/supervisor.rb:281:in `block in supervise'
  2015-10-13 10:40:24 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/supervisor.rb:280:in `fork'
  2015-10-13 10:40:24 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/supervisor.rb:280:in `supervise'
  2015-10-13 10:40:24 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/supervisor.rb:137:in `start'
  2015-10-13 10:40:24 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/command/fluentd.rb:167:in `<top (required)>'
  2015-10-13 10:40:24 +0000 [error]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
  2015-10-13 10:40:24 +0000 [error]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
  2015-10-13 10:40:24 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/bin/fluentd:6:in `<top (required)>'
  2015-10-13 10:40:24 +0000 [error]: /opt/td-agent/embedded/bin/fluentd:23:in `load'
  2015-10-13 10:40:24 +0000 [error]: /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
  2015-10-13 10:40:24 +0000 [error]: /usr/sbin/td-agent:7:in `load'
  2015-10-13 10:40:24 +0000 [error]: /usr/sbin/td-agent:7:in `<main>'
2015-10-13 10:40:24 +0000 [info]: shutting down fluentd
```

It's not a huge issue but unexpected.

Thanks,
Ed.

**Comment by repeatedly** [comment]
It works for on my environment.
Maybe, aws-sdk v2 changes a behaviour and it causes this problem.
Hmm, do you use `us-east-1` region?

**Comment by edjames** [comment]
Yes, I actually push to 2 regions: `us-east-1` and `eu-west-1`

**Comment by repeatedly** [comment]
Does this happen for `us-east-1` setting?

https://github.com/fluent/fluent-plugin-s3/blob/e0c05208783fe6010ffbe8ef82e6755ee0fceaad/lib/fluent/plugin/out_s3.rb#L44

By default, if there is no `AWS_REGION` env, `us-east-1` is used.

**Comment by edjames** [comment]
I'm explicitly setting the region in the config files. I have 2 store config blocks setup, one for each S3 region. Behaviour is the same for both.

If this is working on your env I will try again and make sure I'm not doing anything stupid :)

**Comment by edjames** [comment]
Strangely this now seems to be working fine again. For the life of me I cannot see what was wrong and I can no longer replicate this either.

Thanks for responding anyway.

**Comment by repeatedly** [comment]
> Strangely this now seems to be working fine again.

Good to hear :)
