### ISSUE TITLE
S3 output error

### ISSUE THREAD

**Issue by WilliamBurdett** [fluent/fluent-plugin-s3#139]
I found this error that completely blocked fluent from piping any data into s3. It was still filling its buffers along the way. I found a workaround by creating an empty version of that file and fluent started emptying out its buffers. One emptied correctly, the other only went back 2 days of data instead of 13. 

Any help would be appreciated

```
unexpected error while shutting down output plugins plugin=Fluent::S3Output plugin_id="object:3fa4b1162764" error_class=Errno::ENOENT error=#<Errno::ENOENT: No such file or directory @ sys_fail2 - (/site/fluentd/run/s3.email.2016030501.b52d42c157d319535.log, /site/fluentd/run/s3.email.2016030501.q52d42c157d319535.log)>
  2016-03-17 21:19:00 +0000 [warn]: /site/fluentd/vendor/bundle/ruby/2.1.0/gems/fluentd-0.12.20/lib/fluent/plugin/buf_file.rb:68:in `rename'
  2016-03-17 21:19:00 +0000 [warn]: /site/fluentd/vendor/bundle/ruby/2.1.0/gems/fluentd-0.12.20/lib/fluent/plugin/buf_file.rb:68:in `mv'
  2016-03-17 21:19:00 +0000 [warn]: /site/fluentd/vendor/bundle/ruby/2.1.0/gems/fluentd-0.12.20/lib/fluent/plugin/buf_file.rb:185:in `enqueue'
  2016-03-17 21:19:00 +0000 [warn]: /site/fluentd/vendor/bundle/ruby/2.1.0/gems/fluentd-0.12.20/lib/fluent/buffer.rb:296:in `block (2 levels) in push'
  2016-03-17 21:19:00 +0000 [warn]: /opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
  2016-03-17 21:19:00 +0000 [warn]: /site/fluentd/vendor/bundle/ruby/2.1.0/gems/fluentd-0.12.20/lib/fluent/buffer.rb:295:in `block in push'
  2016-03-17 21:19:00 +0000 [warn]: /opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
  2016-03-17 21:19:00 +0000 [warn]: /site/fluentd/vendor/bundle/ruby/2.1.0/gems/fluentd-0.12.20/lib/fluent/buffer.rb:289:in `push'
  2016-03-17 21:19:00 +0000 [warn]: /site/fluentd/vendor/bundle/ruby/2.1.0/gems/fluentd-0.12.20/lib/fluent/output.rb:544:in `block (2 levels) in configure'
  2016-03-17 21:19:00 +0000 [warn]: /site/fluentd/vendor/bundle/ruby/2.1.0/gems/fluentd-0.12.20/lib/fluent/output.rb:542:in `each'
  2016-03-17 21:19:00 +0000 [warn]: /site/fluentd/vendor/bundle/ruby/2.1.0/gems/fluentd-0.12.20/lib/fluent/output.rb:542:in `block in configure'
  2016-03-17 21:19:00 +0000 [warn]: /site/fluentd/vendor/bundle/ruby/2.1.0/gems/fluentd-0.12.20/lib/fluent/output.rb:579:in `call'
  2016-03-17 21:19:00 +0000 [warn]: /site/fluentd/vendor/bundle/ruby/2.1.0/gems/fluentd-0.12.20/lib/fluent/output.rb:579:in `enqueue_buffer'
  2016-03-17 21:19:00 +0000 [warn]: /site/fluentd/vendor/bundle/ruby/2.1.0/gems/fluentd-0.12.20/lib/fluent/output.rb:297:in `block in try_flush'
  2016-03-17 21:19:00 +0000 [warn]: /opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
  2016-03-17 21:19:00 +0000 [warn]: /site/fluentd/vendor/bundle/ruby/2.1.0/gems/fluentd-0.12.20/lib/fluent/output.rb:295:in `try_flush'
  2016-03-17 21:19:00 +0000 [warn]: /site/fluentd/vendor/bundle/ruby/2.1.0/gems/fluentd-0.12.20/lib/fluent/output.rb:140:in `run'
2016-03-17 21:19:00 +0000 [info]: shutting down output type="s3" plugin_id="object:3fa4b1511d24"
```

**Comment by repeatedly** [comment]
Please paste your configuration here.

**Comment by WilliamBurdett** [comment]
We have 3 log files being filled by apache: access.log, ems-gif-access.log, and display-gif-access.log.

When this issue hit, only ems-gif-access.log stopped working, the other two continued to function normally.

```
<source>
  type tail
  format none
  path /site/click/logs/access.log
  pos_file /site/fluentd/run/access_log.pos
  tag apache.forwarding
</source>
<match apache.forwarding>
  type s3

  aws_key_id '%key%'
  aws_sec_key '%secret%'
  s3_bucket '%bucket%'
  s3_region 'us-east-1'
  path pixel-logs/%Y%m%d/%hostname%-
  buffer_path /site/fluentd/run/s3
  check_apikey_on_start false
  format single_value 
  time_slice_format %Y%m%d%H
  time_slice_wait 10m
  append true
  store_as 'txt'
  utc

  buffer_chunk_limit 256m
</match>

<source>
  type tail
  format none
  path /site/click/logs/ems-gif-access.log
  pos_file /site/fluentd/run/email_access_log.pos
  tag apache.email.forwarding
</source>
<match apache.email.forwarding>
  type s3

  aws_key_id '%key%'
  aws_sec_key '%secret%'
  s3_bucket '%bucket%'
  s3_region 'us-east-1'
  path web-tracking/email-address/%Y%m%d%H/%hostname%-
  buffer_path /site/fluentd/run/s3.email
  check_apikey_on_start false
  format single_value 
  time_slice_format %Y%m%d%H
  time_slice_wait 10m
  append true
  store_as 'txt'
  utc

  buffer_chunk_limit 256m
</match>

<source>
  type tail
  format none
  path /site/click/logs/display-gif-access.log
  pos_file /site/fluentd/run/display-gif-access_log.pos
  tag apache-display.forwarding
</source>
<match apache-display.forwarding>
  type s3

  aws_key_id '%key%'
  aws_sec_key '%secret%'
  s3_bucket '%bucket%'
  s3_region 'us-east-1'
  path pixel-logs/%Y%m%d/%hostname%-
  buffer_path /site/fluentd/run/s3-display
  check_apikey_on_start false
  format single_value 
  time_slice_format %Y%m%d%H
  time_slice_wait 10m
  append true
  store_as 'txt'
  utc

  buffer_chunk_limit 256m
</match>


```

**Comment by repeatedly** [comment]
Maybe, `buffer_path /site/fluentd/run/s3` and `buffer_path /site/fluentd/run/s3.email` setting is a problem.
`/site/fluentd/run/s3` includes `/site/fluentd/run/s3.email` so `/site/fluentd/run/s3` may flush `/site/fluentd/run/s3.email`'s buffer chunks.

I will add this prefix problem to buf_file article.

**Comment by WilliamBurdett** [comment]
Thanks so much, was spinning on this for like a week.
