### ISSUE TITLE
unexpected error while checking flushed chunks

### ISSUE THREAD

**Issue by shawnbutts** [fluent/fluent-plugin-s3#155]
```
unexpected error while checking flushed chunks. ignored. plugin_id="object:3f8f09391890" error_class=NoMethodError error=#<NoMethodError: undefined method `<' for nil:NilClass>
```

seeing this with the fluent 0.14.1

**Comment by repeatedly** [comment]
This doesn't happen with fluentd v0.12 series, right?

**Comment by shawnbutts** [comment]
sorry i missed the question.  correct, this was not an issue with v0.12.  it is still happening with 0.14.6

**Comment by shawnbutts** [comment]
when this happens it appear that it is related to a zero length buffer file.  not sure now the zero lenght file is getting created. but, if it remove it and restart fluent, i do not get the error.

**Comment by repeatedly** [comment]
Could you paste your entire logs?
I want to check stacktrace, not only error message.

**Comment by shawnbutts** [comment]
That was the whole log.

**Comment by repeatedly** [comment]
Hmm... it means your fluentd log doesn't have other logs?

**Comment by philm** [comment]
I ran into the same problem. Cause seems to be a 0 byte buffer.*log.meta file and removing the file + restarting fluentd gets me by.

Here's a stack trace that occurs when the error happens for the first time. 

```
2016-10-18 23:32:18 +0000 [info]: following tail of /log/auth.log
2016-10-18 23:32:18 +0000 [info]: listening syslog socket on 0.0.0.0:5140 with udp
2016-10-18 23:32:18 +0000 [info]: listening fluent socket on 0.0.0.0:24224
2016-10-18 23:32:19 +0000 [error]: unexpected error while checking flushed chunks. ignored. plugin_id="object:3fcff73a3084" error_class=NoMethodError error="undefined method `<' for nil:NilClass"
  2016-10-18 23:32:19 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.8/lib/fluent/plugin/output.rb:1149:in `block in enqueue_thread_run'
  2016-10-18 23:32:19 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.8/lib/fluent/plugin/buffer.rb:355:in `block (2 levels) in enqueue_all'
  2016-10-18 23:32:19 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.8/lib/fluent/plugin/buffer.rb:353:in `each'
  2016-10-18 23:32:19 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.8/lib/fluent/plugin/buffer.rb:353:in `block in enqueue_all'
  2016-10-18 23:32:19 +0000 [error]: /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
  2016-10-18 23:32:19 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.8/lib/fluent/plugin/buffer.rb:351:in `enqueue_all'
  2016-10-18 23:32:19 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.8/lib/fluent/plugin/output.rb:1149:in `enqueue_thread_run'
  2016-10-18 23:32:19 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.8/lib/fluent/plugin_helper/thread.rb:66:in `block in thread_create'
2016-10-18 23:32:24 +0000 [error]: unexpected error while checking flushed chunks. ignored. plugin_id="object:3fcff73a3084" error_class=NoMethodError error="undefined method `<' for nil:NilClass"
```

**Comment by guiocavalcanti** [comment]
I ran into the same problem but I don't have a 0 byte file here =/

**Comment by repeatedly** [comment]
Sorry. I missed philm's comment.
Thanks for the stacktrace!
I will debug it.

**Comment by repeatedly** [comment]
I confirmed 0byte meta file causes this error but hard to find why 0 byte metafile is created...
Need more time to debug it.

@guiocavalcanti Do you ofthen hit this problem with normal metadata / buffers files, right?

**Comment by guiocavalcanti** [comment]
@repeatedly not often. I relaunched my fluentd container and the problem didn't happened. [Here](https://gist.github.com/guiocavalcanti/8bf0ef787ce1aaaf25c3c74262ab8456)'s my config file.

**Comment by breadmj** [comment]
Same issue here! (same error)
In my case, the size of meta files is not exactly 0.
But the size of them is about half of other normal meta files.

**Comment by schasse** [comment]
same issue here.

**Comment by repeatedly** [comment]
This seems the bug of v0.14's buffer and need more time to fix it.
If you hit this problem, please use v0.12 instead of v0.14.

**Comment by repeatedly** [comment]
This issue is moved to fluentd issue. https://github.com/fluent/fluent-plugin-s3/issues/155
