### ISSUE TITLE
Error in hex_random with fluentd 0.14

### ISSUE THREAD

**Issue by stevenc81** [fluent/fluent-plugin-s3#157]
Saw a fix is pushed by @sonots in https://github.com/fluent/fluent-plugin-s3/commit/fc7b4d4e41b6de440910b36eebfc22ba19ada60c. Thanks so much for the amazing job! Curious if there perhaps might be a timeline to release it :D 

`2016-07-27 14:07:13 +0000 [warn]: failed to flush the buffer. plugin_id="object:2ad6d6923e34" retry_time=0 next_retry=2016-07-27 14:07:14 +0000 chunk="5389e757a9fdcba4dadecd7ba3c6150a" error_class=NameError error="uninitialized constant Fluent::FileBufferChunk"
  2016-07-27 14:07:13 +0000 [warn]: /home/fluent/.gem/ruby/2.3.0/gems/fluent-plugin-s3-0.6.8/lib/fluent/plugin/out_s3.rb:271:in `hex_random'
  2016-07-27 14:07:13 +0000 [warn]: /home/fluent/.gem/ruby/2.3.0/gems/fluent-plugin-s3-0.6.8/lib/fluent/plugin/out_s3.rb:200:in `write'
  2016-07-27 14:07:13 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.1/lib/fluent/compat/output.rb:132:in `write'
  2016-07-27 14:07:13 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.1/lib/fluent/plugin/output.rb:787:in `try_flush'
  2016-07-27 14:07:13 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.1/lib/fluent/plugin/output.rb:962:in `flush_thread_run'
  2016-07-27 14:07:13 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.1/lib/fluent/plugin/output.rb:369:in `block (2 levels) in start'
  2016-07-27 14:07:13 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.1/lib/fluent/plugin_helper/thread.rb:66:in `block in thread_create'
2016-07-27 14:07:14 +0000 [warn]: failed to flush the buffer. plugin_id="object:2ad6d6923e34" retry_time=1 next_retry=2016-07-27 14:07:15 +0000 chunk="5389e757a9fdcba4dadecd7ba3c6150a" error_class=NameError error="uninitialized constant Fluent::FileBufferChunk"`

**Comment by repeatedly** [comment]
Released new version including sonots's fix.
