### ISSUE TITLE
[Fluent::S3Input] no block given (yield) on 0.14.6

### ISSUE THREAD

**Issue by JoeOrtiz** [fluent/fluent-plugin-s3#165]
I keep getting this error on startup when trying to use the s3 input:

```
Sep 27 19:49:44 i-b84b4365@type parserbash[29417]: 2016-09-27 19:49:44 +0000 [warn]: [Fluent::S3Input] no block given (yield)
Sep 27 19:49:44 i-b84b4365@type parserbash[29417]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/plugin/parser_json.rb:73:in `parse'
Sep 27 19:49:44 i-b84b4365@type parserbash[29417]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-s3-0.7.1/lib/fluent/plugin/in_s3.rb:221:in `block in process'
Sep 27 19:49:44 i-b84b4365@type parserbash[29417]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-s3-0.7.1/lib/fluent/plugin/in_s3.rb:220:in `each_line'
Sep 27 19:49:44 i-b84b4365@type parserbash[29417]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-s3-0.7.1/lib/fluent/plugin/in_s3.rb:220:in `process'
Sep 27 19:49:44 i-b84b4365@type parserbash[29417]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-s3-0.7.1/lib/fluent/plugin/in_s3.rb:149:in `block in run'
Sep 27 19:49:44 i-b84b4365@type parserbash[29417]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.6.3/lib/aws-sdk-resources/services/sqs/queue_poller.rb:413:in `block in yield_messages'
Sep 27 19:49:44 i-b84b4365@type parserbash[29417]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.6.3/lib/aws-sdk-resources/services/sqs/queue_poller.rb:412:in `each'
Sep 27 19:49:44 i-b84b4365@type parserbash[29417]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.6.3/lib/aws-sdk-resources/services/sqs/queue_poller.rb:412:in `yield_messages'
Sep 27 19:49:44 i-b84b4365@type parserbash[29417]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.6.3/lib/aws-sdk-resources/services/sqs/queue_poller.rb:405:in `block in process_messages'
Sep 27 19:49:44 i-b84b4365@type parserbash[29417]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.6.3/lib/aws-sdk-resources/services/sqs/queue_poller.rb:404:in `catch'
Sep 27 19:49:44 i-b84b4365@type parserbash[29417]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.6.3/lib/aws-sdk-resources/services/sqs/queue_poller.rb:404:in `process_messages'
Sep 27 19:49:44 i-b84b4365@type parserbash[29417]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.6.3/lib/aws-sdk-resources/services/sqs/queue_poller.rb:336:in `block (2 levels) in poll'
Sep 27 19:49:44 i-b84b4365@type parserbash[29417]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.6.3/lib/aws-sdk-resources/services/sqs/queue_poller.rb:331:in `loop'
Sep 27 19:49:44 i-b84b4365@type parserbash[29417]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.6.3/lib/aws-sdk-resources/services/sqs/queue_poller.rb:331:in `block in poll'
Sep 27 19:49:44 i-b84b4365@type parserbash[29417]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.6.3/lib/aws-sdk-resources/services/sqs/queue_poller.rb:330:in `catch'
Sep 27 19:49:44 i-b84b4365@type parserbash[29417]: /usr/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.6.3/lib/aws-sdk-resources/services/sqs/queue_poller.rb:330:in `poll'
Sep 27 19:49:44 i-b84b4365@type parserbash[29417]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-s3-0.7.1/lib/fluent/plugin/in_s3.rb:144:in `run'

```

Any idea on what might be causing this?

**Comment by repeatedly** [comment]
Does this also happen with v0.12?

**Comment by JoeOrtiz** [comment]
Just tested it on fluentd-0.12.29, and it works, but not on v0.14.x

**Comment by repeatedly** [comment]
Thanks!
I will check it later.

**Comment by repeatedly** [comment]
https://github.com/fluent/fluent-plugin-s3/pull/171 fixes this problem.
