### ISSUE TITLE
Error on adding s3 output to fluentd in container

### ISSUE THREAD

**Issue by parkjaeman** [fluent/fluent-plugin-s3#176]
I am trying to add s3 output on fluentd in kubernetes and met following error.
Please let me know what is problem?

-------------------------------------

2016-11-23 05:50:02 +0000 [info]: reading config file path="/etc/td-agent/td-agent.conf"
2016-11-23 05:50:02 +0000 [info]: starting fluentd-0.12.29
2016-11-23 05:50:02 +0000 [info]: gem 'fluent-mixin-config-placeholders' version '0.4.0'
2016-11-23 05:50:02 +0000 [info]: gem 'fluent-mixin-plaintextformatter' version '0.2.6'
2016-11-23 05:50:02 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '1.5.0'
2016-11-23 05:50:02 +0000 [info]: gem 'fluent-plugin-kafka' version '0.3.5'
2016-11-23 05:50:02 +0000 [info]: gem 'fluent-plugin-kafka' version '0.3.1'
2016-11-23 05:50:02 +0000 [info]: gem 'fluent-plugin-mongo' version '0.7.15'
2016-11-23 05:50:02 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '1.5.5'
2016-11-23 05:50:02 +0000 [info]: gem 'fluent-plugin-s3' version '0.7.2'
2016-11-23 05:50:02 +0000 [info]: gem 'fluent-plugin-s3' version '0.7.1'
2016-11-23 05:50:02 +0000 [info]: gem 'fluent-plugin-scribe' version '0.10.14'
2016-11-23 05:50:02 +0000 [info]: gem 'fluent-plugin-td' version '0.10.29'
2016-11-23 05:50:02 +0000 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.2'
2016-11-23 05:50:02 +0000 [info]: gem 'fluent-plugin-webhdfs' version '0.4.2'
2016-11-23 05:50:02 +0000 [info]: gem 'fluentd' version '0.12.29'
2016-11-23 05:50:02 +0000 [info]: adding match pattern="fluent.**" type="null"
2016-11-23 05:50:02 +0000 [info]: adding match pattern="*.**" type="s3"
2016-11-23 05:50:02 +0000 [error]: unexpected error error="No such file or directory - addr"
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:587:in ``'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:587:in `ifconfig'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:634:in `mac_address'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:242:in `block in timestamp_create'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:232:in `synchronize'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/uuidtools-2.1.5/lib/uuidtools.rb:232:in `timestamp_create'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-mixin-config-placeholders-0.4.0/lib/fluent/mixin/config_placeholders.rb:37:in `uuid_timestamp'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-mixin-config-placeholders-0.4.0/lib/fluent/mixin/config_placeholders.rb:80:in `block (2 levels) in configure'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-mixin-config-placeholders-0.4.0/lib/fluent/mixin/config_placeholders.rb:41:in `call'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-mixin-config-placeholders-0.4.0/lib/fluent/mixin/config_placeholders.rb:41:in `block in replace'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-mixin-config-placeholders-0.4.0/lib/fluent/mixin/config_placeholders.rb:41:in `each'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-mixin-config-placeholders-0.4.0/lib/fluent/mixin/config_placeholders.rb:41:in `reduce'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-mixin-config-placeholders-0.4.0/lib/fluent/mixin/config_placeholders.rb:41:in `replace'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-mixin-config-placeholders-0.4.0/lib/fluent/mixin/config_placeholders.rb:96:in `block in configure'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-mixin-config-placeholders-0.4.0/lib/fluent/mixin/config_placeholders.rb:105:in `call'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-mixin-config-placeholders-0.4.0/lib/fluent/mixin/config_placeholders.rb:105:in `configure'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-s3-0.7.2/lib/fluent/plugin/out_s3.rb:130:in `configure'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/agent.rb:133:in `add_match'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/agent.rb:64:in `block in configure'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/agent.rb:57:in `each'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/agent.rb:57:in `configure'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/root_agent.rb:86:in `configure'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/engine.rb:129:in `configure'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/engine.rb:103:in `run_configure'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/supervisor.rb:489:in `run_configure'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/supervisor.rb:160:in `block in start'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/supervisor.rb:366:in `call'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/supervisor.rb:366:in `main_process'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/supervisor.rb:339:in `block in supervise'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/supervisor.rb:338:in `fork'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/supervisor.rb:338:in `supervise'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/supervisor.rb:156:in `start'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.29/bin/fluentd:5:in `<top (required)>'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/bin/fluentd:23:in `load'
  2016-11-23 05:50:02 +0000 [error]: /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
  2016-11-23 05:50:02 +0000 [error]: /usr/sbin/td-agent:7:in `load'
  2016-11-23 05:50:02 +0000 [error]: /usr/sbin/td-agent:7:in `<main>'
2016-11-23 05:50:02 +0000 [info]: process finished code=256
2016-11-23 05:50:02 +0000 [warn]: process died within 1 second. exit.

**Comment by repeatedly** [comment]
This is the bug of uuidtools and there is no response from uuidtools author.
Hmm... time to remove config-placeholder mixin.

**Comment by repeatedly** [comment]
I released v0.8.0.rc1 to resolve this problem.
Could you try this version? You need `--pre` in install command.
