### ISSUE TITLE
"both utc and local time are specified"

### ISSUE THREAD

**Issue by brandonmp** [fluent/fluent-plugin-s3#178]
I've been setting this extension up & it's been working fine, but now it's throwing fatal errors on run. As far as I can recall I haven't changed anything in the `conf`, so hoping someone may have some insight.

I'm certain it's the `s3` plugin b/c removing it from `conf` fixes the error

the error on-build:

```
2016-11-28 19:51:12 +0000 [info]: reading config file path="/fluentd/etc/fluent.conf"
2016-11-28 19:51:12 +0000 [info]: starting fluentd-0.14.9
2016-11-28 19:51:12 +0000 [info]: spawn command to main: /usr/bin/ruby -Eascii-8bit:ascii-8bit /home/fluent/.gem/ruby/2.3.0/bin/fluentd -c /fluentd/etc/fluent.conf -p /fluentd/plugins --under-su
pervisor
2016-11-28 19:51:12 +0000 [info]: reading config file path="/fluentd/etc/fluent.conf"
2016-11-28 19:51:12 +0000 [info]: starting fluentd-0.14.9 without supervision
2016-11-28 19:51:12 +0000 [info]: gem 'fluent-mixin-config-placeholders' version '0.4.0'
2016-11-28 19:51:12 +0000 [info]: gem 'fluent-plugin-concat' version '2.0.0'
2016-11-28 19:51:12 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '1.9.0'
2016-11-28 19:51:12 +0000 [info]: gem 'fluent-plugin-s3' version '0.7.2'
2016-11-28 19:51:12 +0000 [info]: gem 'fluent-plugin-secure-forward' version '0.4.3'
2016-11-28 19:51:12 +0000 [info]: gem 'fluentd' version '0.14.9'
2016-11-28 19:51:12 +0000 [info]: gem 'fluentd' version '0.12.29'
2016-11-28 19:51:12 +0000 [info]: adding match in @mainstream pattern="**" type="copy"
2016-11-28 19:51:13 +0000 [**error**]: config error file="/fluentd/etc/fluent.conf" error="both of utc and localtime are specified, use only one of them"
2016-11-28 19:51:13 +0000 [info]: Worker 0 finished unexpectedly with status 2
2016-11-28 19:51:13 +0000 [info]: Received graceful stop
```

It looks like a straightforward message, but I'm clueless as to how to fix it.  My `fluent.conf` is pretty simple:

```
<source>
  @type  forward
  @id    input1
  @label @mainstream
  port  24224
</source>
<label @mainstream>
<match **>
  @type copy
  <store>
    @type s3
    aws_key_id //
    aws_sec_key //
    s3_bucket my-fluentd-logs
    s3_region us-east-1
    s3_object_key_format %{path}%{time_slice}_%{index}.%{file_extension}
    path ${tag}/
    buffer_path /fluentd/buffer
    flush_at_shutdown true
    store_as json
    formatter json
    utc 
    include_time_key true
    time_key log_time # default is time
    time_slice_format %Y%m%d%H 
    time_slice_wait 5m # wait this many (s)ec/(m)in after chunk window closes to formally close chunk, for late arrivals
  </store>
  <store>
    @type elasticsearch
    host logsene-receiver.sematext.com
    port 443
    scheme https
    index_name some_index
    buffer_type file
    buffer_path /tmp/fluent/es-buffer/es.all.*.buffer
    buffer_chunk_limit 250k
    flush_interval 50s
    retry_limit 5
    retry_wait 60
    num_threads 1
  </store>
</match>
</label>
```

When I run it w/o the `utc` option, messages I send to `fluentd` from my `node app` throw errors as well:

```
// the message
{"name":"a-node-app","hostname":"my-host","pid":24378,"level":30,"event":"CLUSTER_STARTED","numWorkers":1,"msg":"","time":"2016-11-28T19:55:45.215Z","v":0}


// the fluentd console
2016-11-28 19:55:45 +0000 [warn]: emit transaction failed: error_class=ArgumentError error="time must be a Fluent::EventTime (or Integer): Float" tag="bunyan"
  2016-11-28 19:55:45 +0000 [warn]: /home/fluent/.gem/ruby/2.3.0/gems/fluentd-0.14.9/lib/fluent/plugin/output.rb:723:in `metadata'
  2016-11-28 19:55:45 +0000 [warn]: /home/fluent/.gem/ruby/2.3.0/gems/fluentd-0.14.9/lib/fluent/plugin/output.rb:838:in `block in handle_stream_with_custom_format'
  2016-11-28 19:55:45 +0000 [warn]: /home/fluent/.gem/ruby/2.3.0/gems/fluentd-0.14.9/lib/fluent/event.rb:107:in `each'
  2016-11-28 19:55:45 +0000 [warn]: /home/fluent/.gem/ruby/2.3.0/gems/fluentd-0.14.9/lib/fluent/plugin/output.rb:837:in `handle_stream_with_custom_format'
  2016-11-28 19:55:45 +0000 [warn]: /home/fluent/.gem/ruby/2.3.0/gems/fluentd-0.14.9/lib/fluent/plugin/output.rb:771:in `execute_chunking'
  2016-11-28 19:55:45 +0000 [warn]: /home/fluent/.gem/ruby/2.3.0/gems/fluentd-0.14.9/lib/fluent/plugin/output.rb:706:in `emit_buffered'
  2016-11-28 19:55:45 +0000 [warn]: /home/fluent/.gem/ruby/2.3.0/gems/fluentd-0.14.9/lib/fluent/plugin/out_copy.rb:38:in `block in process'
  2016-11-28 19:55:45 +0000 [warn]: /home/fluent/.gem/ruby/2.3.0/gems/fluentd-0.14.9/lib/fluent/plugin/out_copy.rb:37:in `each'
  2016-11-28 19:55:45 +0000 [warn]: /home/fluent/.gem/ruby/2.3.0/gems/fluentd-0.14.9/lib/fluent/plugin/out_copy.rb:37:in `process'
  2016-11-28 19:55:45 +0000 [warn]: /home/fluent/.gem/ruby/2.3.0/gems/fluentd-0.14.9/lib/fluent/plugin/multi_output.rb:147:in `emit_sync'
  2016-11-28 19:55:45 +0000 [warn]: /home/fluent/.gem/ruby/2.3.0/gems/fluentd-0.14.9/lib/fluent/event_router.rb:90:in `emit_stream'
  2016-11-28 19:55:45 +0000 [warn]: /home/fluent/.gem/ruby/2.3.0/gems/fluentd-0.14.9/lib/fluent/event_router.rb:81:in `emit'
  2016-11-28 19:55:45 +0000 [warn]: /home/fluent/.gem/ruby/2.3.0/gems/fluentd-0.14.9/lib/fluent/plugin/in_forward.rb:324:in `on_message'
  2016-11-28 19:55:45 +0000 [warn]: /home/fluent/.gem/ruby/2.3.0/gems/fluentd-0.14.9/lib/fluent/plugin/in_forward.rb:201:in `block in handle_connection'
  2016-11-28 19:55:45 +0000 [warn]: /home/fluent/.gem/ruby/2.3.0/gems/fluentd-0.14.9/lib/fluent/plugin/in_forward.rb:232:in `block (2 levels) in read_messages'
  2016-11-28 19:55:45 +0000 [warn]: /home/fluent/.gem/ruby/2.3.0/gems/fluentd-0.14.9/lib/fluent/plugin/in_forward.rb:236:in `<<'
  2016-11-28 19:55:45 +0000 [warn]: /home/fluent/.gem/ruby/2.3.0/gems/fluentd-0.14.9/lib/fluent/plugin/in_forward.rb:236:in `block (2 levels) in read_messages'
  2016-11-28 19:55:45 +0000 [warn]: /home/fluent/.gem/ruby/2.3.0/gems/fluentd-0.14.9/lib/fluent/plugin/in_forward.rb:250:in `block in read_messages'
  2016-11-28 19:55:45 +0000 [warn]: /home/fluent/.gem/ruby/2.3.0/gems/fluentd-0.14.9/lib/fluent/plugin/in_forward.rb:480:in `on_read'
  2016-11-28 19:55:45 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.4.5/lib/cool.io/io.rb:123:in `on_readable'
  2016-11-28 19:55:45 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.4.5/lib/cool.io/io.rb:186:in `on_readable'
  2016-11-28 19:55:45 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.4.5/lib/cool.io/loop.rb:88:in `run_once'
  2016-11-28 19:55:45 +0000 [warn]: /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.4.5/lib/cool.io/loop.rb:88:in `run'
  2016-11-28 19:55:45 +0000 [warn]: /home/fluent/.gem/ruby/2.3.0/gems/fluentd-0.14.9/lib/fluent/plugin_helper/event_loop.rb:71:in `block in start'
  2016-11-28 19:55:45 +0000 [warn]: /home/fluent/.gem/ruby/2.3.0/gems/fluentd-0.14.9/lib/fluent/plugin_helper/thread.rb:66:in `block in thread_create'
2016-11-28 19:55:45 +0000 [error]: unexpected error on reading data from client address="172.17.0.1" error_class=ArgumentError error="time must be a Fluent::EventTime (or Integer): Float"
  2016-11-28 19:55:45 +0000 [error]: suppressed same stacktrace
```

**Comment by brandonmp** [comment]
and in record time, i figured it out. I had added `fluent-plugin-concat` to my dockerfile, but decided not to include it in my `fluent.conf`

Apparently just its inclusion in the build was enough to break stuff--unsure exactly why since i never got around to using the `concat` plugin.

**Comment by repeatedly** [comment]
This has been already fixed at the master: https://github.com/fluent/fluentd/pull/1319
v0.14.10 fixes this problem.
