### ISSUE TITLE
Use IAM role from AWS metadata

### ISSUE THREAD

**Issue by luqasz** [fluent/fluent-plugin-s3#198]
Hi.

I am trying to run this plugin with EC2 instance and its IAM role. `instance_profile_credentials ` throws an error:
```
2017-06-23 14:50:40 +0000 [error]: unexpected error error_class=RuntimeError error=#<RuntimeError: can't call S3 API. Please check your aws_key_id / aws_sec_key or s3_region configuration. error = #<Aws::S3::Errors::AccessDenied: Access Denied>>
  2017-06-23 14:50:40 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-s3-0.8.2/lib/fluent/plugin/out_s3.rb:350:in `rescue in check_apikeys'
  2017-06-23 14:50:40 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-s3-0.8.2/lib/fluent/plugin/out_s3.rb:346:in `check_apikeys'
  2017-06-23 14:50:40 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-s3-0.8.2/lib/fluent/plugin/out_s3.rb:190:in `start'
  2017-06-23 14:50:40 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/agent.rb:71:in `block in start'
  2017-06-23 14:50:40 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/agent.rb:70:in `each'
  2017-06-23 14:50:40 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/agent.rb:70:in `start'
  2017-06-23 14:50:40 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/root_agent.rb:108:in `start'
  2017-06-23 14:50:40 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/engine.rb:237:in `start'
  2017-06-23 14:50:40 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/engine.rb:187:in `run'
  2017-06-23 14:50:40 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:570:in `run_engine'
  2017-06-23 14:50:40 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:162:in `block in start'
  2017-06-23 14:50:40 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:366:in `call'
  2017-06-23 14:50:40 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:366:in `main_process'
  2017-06-23 14:50:40 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:339:in `block in supervise'
  2017-06-23 14:50:40 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:338:in `fork'
  2017-06-23 14:50:40 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:338:in `supervise'
  2017-06-23 14:50:40 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:156:in `start'
  2017-06-23 14:50:40 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
  2017-06-23 14:50:40 +0000 [error]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2017-06-23 14:50:40 +0000 [error]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2017-06-23 14:50:40 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/bin/fluentd:5:in `<top (required)>'
  2017-06-23 14:50:40 +0000 [error]: /opt/td-agent/embedded/bin/fluentd:23:in `load'
  2017-06-23 14:50:40 +0000 [error]: /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
  2017-06-23 14:50:40 +0000 [error]: /usr/sbin/td-agent:7:in `load'
  2017-06-23 14:50:40 +0000 [error]: /usr/sbin/td-agent:7:in `<main>'
2017-06-23 14:50:40 +0000 [info]: shutting down fluentd
2017-06-23 14:50:40 +0000 [info]: process finished code=0
2017-06-23 14:50:40 +0000 [warn]: process died within 1 second. exit.```
I have a empty section
```<instance_profile_credentials>
</instance_profile_credentials>``` in my config file.

td-agent debian version `2.3.5-0`
s3 plugin version `0.8.1`

**Comment by luqasz** [comment]
Ah. NVM. I've made a mistake in IAM policy. All works fine.
