### ISSUE TITLE
[warn]:  error=#<NoMethodError: undefined method `delete' for nil:NilClass>

### ISSUE THREAD

**Issue by AlexMorreale** [fluent/fluent-plugin-s3#204]
```
2017-08-24 15:11:33 +0000 [warn]:  error=#<NoMethodError: undefined method `delete' for nil:NilClass>
  2017-08-24 15:11:33 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/parser.rb:276:in `parse'
  2017-08-24 15:11:33 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-s3-0.8.2/lib/fluent/plugin/in_s3.rb:237:in `block in process'
  2017-08-24 15:11:33 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-s3-0.8.2/lib/fluent/plugin/in_s3.rb:236:in `each_line'
  2017-08-24 15:11:33 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-s3-0.8.2/lib/fluent/plugin/in_s3.rb:236:in `process'
  2017-08-24 15:11:33 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-s3-0.8.2/lib/fluent/plugin/in_s3.rb:155:in `block in run'
  2017-08-24 15:11:33 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.9.9/lib/aws-sdk-resources/services/sqs/queue_poller.rb:413:in `block in yield_messages'
  2017-08-24 15:11:33 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.9.9/lib/aws-sdk-resources/services/sqs/queue_poller.rb:412:in `each'
  2017-08-24 15:11:33 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.9.9/lib/aws-sdk-resources/services/sqs/queue_poller.rb:412:in `yield_messages'
  2017-08-24 15:11:33 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.9.9/lib/aws-sdk-resources/services/sqs/queue_poller.rb:405:in `block in process_messages'
  2017-08-24 15:11:33 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.9.9/lib/aws-sdk-resources/services/sqs/queue_poller.rb:404:in `catch'
  2017-08-24 15:11:33 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.9.9/lib/aws-sdk-resources/services/sqs/queue_poller.rb:404:in `process_messages'
  2017-08-24 15:11:33 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.9.9/lib/aws-sdk-resources/services/sqs/queue_poller.rb:336:in `block (2 levels) in poll'
  2017-08-24 15:11:33 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.9.9/lib/aws-sdk-resources/services/sqs/queue_poller.rb:331:in `loop'
  2017-08-24 15:11:33 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.9.9/lib/aws-sdk-resources/services/sqs/queue_poller.rb:331:in `block in poll'
  2017-08-24 15:11:33 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.9.9/lib/aws-sdk-resources/services/sqs/queue_poller.rb:330:in `catch'
  2017-08-24 15:11:33 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.9.9/lib/aws-sdk-resources/services/sqs/queue_poller.rb:330:in `poll'
  2017-08-24 15:11:33 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-s3-0.8.2/lib/fluent/plugin/in_s3.rb:149:in `run'
```

Getting this error when trying to input from s3

```
<source>
  type s3
  tag log.<%= node["environment"] %>.ssl.cloudflare.com
  s3_bucket <%= node["fluentd"]["aggregator"]["cloudflare_s3_bucket"] %>
  s3_region us-east-1
  store_as json
  format json
  <sqs>
    queue_name <%= node["fluentd"]["aggregator"]["cloudflare_s3_event_sqs_url"] %>
  </sqs>
</source>
```

Can someone point me in the right direction here?

**Comment by AlexMorreale** [comment]
Looks like the json i had in s3 was malformed sorry for the issue
