### ISSUE TITLE
Temporarily failed to flush the buffer due to networking error

### ISSUE THREAD

**Issue by akalbhor** [fluent/fluent-plugin-s3#215]
Hi, 
I am using out_s3 plugin for a while and suddenly got a networking issue causing the flush to fail. The retry succeeded eventually after filling up the logs with exception's stack trace. Is there a neat way to handle such issues?
Can the retry succeeded log message be set at "info" level rather than "warn" level, because technically it is a successful recovery?

```
2017-11-02 04:27:50 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2017-11-02 04:23:45 +0000 error_class="Seahorse::Client::NetworkingError" error="execution expired" plugin_id="object:f145b4"
  2017-11-02 04:27:50 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http.rb:879:in `initialize'
  2017-11-02 04:27:50 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http.rb:879:in `open'
  2017-11-02 04:27:50 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http.rb:879:in `block in connect'
  2017-11-02 04:27:50 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/timeout.rb:90:in `block in timeout'
  2017-11-02 04:27:50 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/timeout.rb:100:in `call'
  2017-11-02 04:27:50 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/timeout.rb:100:in `timeout'
  2017-11-02 04:27:50 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http.rb:878:in `connect'
  2017-11-02 04:27:50 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
  2017-11-02 04:27:50 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/net/http.rb:858:in `start'
  2017-11-02 04:27:50 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.9.9/lib/seahorse/client/net_http/connection_pool.rb:285:in `start_session'
  2017-11-02 04:27:50 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.9.9/lib/seahorse/client/net_http/connection_pool.rb:92:in `session_for'
  2017-11-02 04:27:50 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.9.9/lib/seahorse/client/net_http/handler.rb:119:in `session'
  2017-11-02 04:27:50 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.9.9/lib/seahorse/client/net_http/handler.rb:71:in `transmit'
```

Retry succeeded log:

```
2017-11-02 04:28:27 +0000 [warn]: retry succeeded. plugin_id="object:f145b4"
```

**Comment by repeatedly** [comment]
If the retry is succeeded, it is no problem.
This is why fluentd has buffer and retry mechanizm.

**Comment by akalbhor** [comment]
Thanks!
Is there a way in out_s3 plugin to log succeesful flush?
