### ISSUE TITLE
fluent-plugin-s3 sometimes causes Zlib::DataError

### ISSUE THREAD

**Issue by mochizuki-masao** [fluent/fluent-plugin-s3#223]
Hi,

fluent-plugin-s3 start to emit warning occasionally since I have updated fluentd from v0.12 to v1. I'm using `v1.1.0-debian` docker image provided in DockerHub.

```
failed to flush the buffer. retry_time=0 next_retry_seconds=2018-01-30 06:16:02 +0000 chunk="563f8368970c1de01cd924eacce3a69e" error_class=Zlib::DataError error="data error"

/var/lib/gems/2.3.0/gems/fluent-plugin-s3-1.1.1/lib/fluent/plugin/out_s3.rb:498:in `finish'
/var/lib/gems/2.3.0/gems/fluent-plugin-s3-1.1.1/lib/fluent/plugin/out_s3.rb:498:in `compress'
/var/lib/gems/2.3.0/gems/fluent-plugin-s3-1.1.1/lib/fluent/plugin/out_s3.rb:288:in `write'
/var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin/output.rb:1094:in `try_flush'
/var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin/output.rb:1319:in `flush_thread_run'
/var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin/output.rb:439:in `block (2 levels) in start'
/var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'

retry succeeded. chunk_id="563f8368970c1de01cd924eacce3a69e"
```

I found:

1. I can find this warnings especially in high load server.
2. retry just after this warning always succeeds.

Is this a bug for GzipCompressor or a problem of my configuration?

(partial) configuration is below:

```
<match **>
  @type s3
  s3_bucket "#{ENV['LOG_BUCKET_NAME']}"
  s3_region "#{ENV['AWS_REGION']}"
  format json
  path applications/${service}/${log_type}/
  s3_object_key_format %{path}%{time_slice}_${container_id}_%{index}.%{file_extension}
  time_slice_format %Y/%m/%d/%H/%M
  utc
  <buffer time,service,log_type,container_id>
    @type memory
    timekey 5m
    timekey_wait 1m
  </buffer>
</match>
```

**Comment by tjinjin** [comment]
該当の箇所はここかー https://github.com/fluent/fluent-plugin-s3/blob/master/lib/fluent/plugin/out_s3.rb#L498

高負荷時にデータが不正な形になっちゃうようなバグがあるんですかねー

**Comment by repeatedly** [comment]
Hmm... compression code is same between v0.12 and v1.
So if the problem happens, the major cause seems gzip library and buffer chunk combination.
To find the root cause, we need more time to investigate it.

**Comment by eagletmt** [comment]
Same here. I'm using td-agent 3.1.1-0 package in Ubuntu 16.04.
In lmost every flush interval, some of chunks fail to flush with `error_class=Zlib::DataError error="data error"` and succeed to flush in the next retry.

My configuration is like the following.

```
<match logs.*>
  @type s3
  s3_bucket logs-bucket
  s3_region ap-northeast-1
  path ${tag[1]}/%Y/%m/%d/
  s3_object_key_format %{path}%{time_slice}_%{index}_%{uuid_flush}.%{file_extension}

  <buffer tag,time>
    @type file
    path /path/to/s3_buffer
    timekey 1m
    timekey_wait 2m
    timekey_use_utc true
  </buffer>
  <format>
    @type json
  </format>
</match>
```

/path/to/s3_buffer contains about 100 - 150 buffer files.

**Comment by JamesJJ** [comment]
Another "me too":

```
2018-03-26, 10:32:04.078 [warn]: #0 failed to flush the buffer. retry_time=0
                 next_retry_seconds=2018-03-26 02:32:14 +0000
                 chunk="5684790aef8f4a29cacf540b0be5cb75"
                 error_class=Zlib::DataError error="data error"
2018-03-26, 10:32:04.078 [warn]: #0 suppressed same stacktrace
2018-03-26, 10:32:04.101 [warn]: #0 retry succeeded. chunk_id="5684790b6c74eef9982142daa1c3f774"
```

Also, see these messages:

```
2018-03-26, 10:32:38.482 zlib(finalizer): the stream state was inconsistent.
2018-03-26, 10:32:38.482 zlib(finalizer): Zlib::GzipWriter object must be closed explicitly.
```

**Comment by zac-nixon** [comment]
I was able to get around this Zlib::DataError by using fluentd:v0.12.38 then upgrading the fluentd gem

```
RUN gem install fluentd:1.1.2 

RUN gem uninstall fluentd --version '<1.0.0'
```

The v1 docker image uses ruby 2.4.X while 0.12.38 uses 2.3.6. So, it looks like some regression in the ruby zlib library.

**Comment by repeatedly** [comment]
> 2018-03-26, 10:32:38.482 zlib(finalizer): the stream state was inconsistent.
> 2018-03-26, 10:32:38.482 zlib(finalizer): Zlib::GzipWriter object must be closed explicitly.

Maybe, this message is caused by above Zlib::DataError. We need to setup reproduce environment for investigating the problem.

**Comment by jl2005** [comment]
Hi, I have same problem

**config:**

```
<match **>
   @type kafka_buffered

   brokers "#{ENV['FLUENT_KAFKA_BROKERS']}"
   default_topic k8s_unexpected-logs
   #get_kafka_client_log true

   output_include_tag false
   output_include_time false
   exclude_topic_key false
   exclude_partition_key true

   output_data_type json

   buffer_type file
   buffer_path /var/log/td-agent/buffer/td
   buffer_chunk_limit 64M
   buffer_queue_limit 512
   flush_interval 3s

   kafka_agg_max_bytes 1M
   compression_codec gzip
   required_acks 1
   num_threads 4
   max_send_retries 3
   max_retry_wait 10
   disable_retry_limit
</match>
```
**Error message**

```
2018-05-03 21:37:27 +0800 [warn]: Send exception occurred: data error
2018-05-03 21:37:27 +0800 [warn]: Exception Backtrace : /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/gzip_codec.rb:17:in `close'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/gzip_codec.rb:17:in `compress'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/compressor.rb:54:in `block in compress_data'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/instrumenter.rb:21:in `instrument'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/compressor.rb:53:in `compress_data'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/compressor.rb:37:in `compress'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/produce_operation.rb:89:in `block (2 levels) in send_buffered_messages'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/message_buffer.rb:44:in `block (2 levels) in each'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/message_buffer.rb:43:in `each'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/message_buffer.rb:43:in `block in each'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/message_buffer.rb:42:in `each'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/message_buffer.rb:42:in `each'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/produce_operation.rb:87:in `block in send_buffered_messages'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/produce_operation.rb:81:in `each'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/produce_operation.rb:81:in `send_buffered_messages'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/produce_operation.rb:47:in `block in execute'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/instrumenter.rb:21:in `instrument'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/produce_operation.rb:41:in `execute'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/producer.rb:298:in `block in deliver_messages_with_retries'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/producer.rb:286:in `loop'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/producer.rb:286:in `deliver_messages_with_retries'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/producer.rb:236:in `block in deliver_messages'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/instrumenter.rb:21:in `instrument'
/var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/producer.rb:229:in `deliver_messages'
/var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.7.2/lib/fluent/plugin/out_kafka_buffered.rb:277:in `deliver_messages'
/var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.7.2/lib/fluent/plugin/out_kafka_buffered.rb:340:in `write'
/var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/compat/output.rb:131:in `write'
/var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin/output.rb:1094:in `try_flush'
/var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin/output.rb:1319:in `flush_thread_run'
/var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin/output.rb:439:in `block (2 levels) in start'
/var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2018-05-03 21:37:27 +0800 [warn]: failed to flush the buffer. retry_time=0 next_retry_seconds=2018-05-03 21:37:28 +0800 chunk="56b4d4da7cedcc19f3b27fce376f1a63" error_class=Zlib::DataError error="data error"
  2018-05-03 21:37:27 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/gzip_codec.rb:17:in `close'
  2018-05-03 21:37:27 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/gzip_codec.rb:17:in `compress'
  2018-05-03 21:37:27 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/compressor.rb:54:in `block in compress_data'
  2018-05-03 21:37:27 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/instrumenter.rb:21:in `instrument'
  2018-05-03 21:37:27 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/compressor.rb:53:in `compress_data'
  2018-05-03 21:37:27 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/compressor.rb:37:in `compress'
  2018-05-03 21:37:27 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/produce_operation.rb:89:in `block (2 levels) in send_buffered_messages'
  2018-05-03 21:37:27 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/message_buffer.rb:44:in `block (2 levels) in each'
  2018-05-03 21:37:27 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/message_buffer.rb:43:in `each'
  2018-05-03 21:37:27 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/message_buffer.rb:43:in `block in each'
  2018-05-03 21:37:27 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/message_buffer.rb:42:in `each'
  2018-05-03 21:37:27 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/message_buffer.rb:42:in `each'
  2018-05-03 21:37:27 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/produce_operation.rb:87:in `block in send_buffered_messages'
  2018-05-03 21:37:27 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/produce_operation.rb:81:in `each'
  2018-05-03 21:37:27 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/produce_operation.rb:81:in `send_buffered_messages'
  2018-05-03 21:37:27 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/produce_operation.rb:47:in `block in execute'
  2018-05-03 21:37:27 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/instrumenter.rb:21:in `instrument'
  2018-05-03 21:37:27 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/produce_operation.rb:41:in `execute'
  2018-05-03 21:37:27 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/producer.rb:298:in `block in deliver_messages_with_retries'
  2018-05-03 21:37:27 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/producer.rb:286:in `loop'
  2018-05-03 21:37:27 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/producer.rb:286:in `deliver_messages_with_retries'
  2018-05-03 21:37:27 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/producer.rb:236:in `block in deliver_messages'
  2018-05-03 21:37:27 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/instrumenter.rb:21:in `instrument'
  2018-05-03 21:37:27 +0800 [warn]: /var/lib/gems/2.3.0/gems/ruby-kafka-0.5.5/lib/kafka/producer.rb:229:in `deliver_messages'
  2018-05-03 21:37:27 +0800 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.7.2/lib/fluent/plugin/out_kafka_buffered.rb:277:in `deliver_messages'
  2018-05-03 21:37:27 +0800 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-kafka-0.7.2/lib/fluent/plugin/out_kafka_buffered.rb:340:in `write'
  2018-05-03 21:37:27 +0800 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/compat/output.rb:131:in `write'
  2018-05-03 21:37:27 +0800 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin/output.rb:1094:in `try_flush'
  2018-05-03 21:37:27 +0800 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin/output.rb:1319:in `flush_thread_run'
  2018-05-03 21:37:27 +0800 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin/output.rb:439:in `block (2 levels) in start'
  2018-05-03 21:37:27 +0800 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2018-05-03 21:37:28 +0800 [warn]: retry succeeded. chunk_id="56b4d4db28399274b5bb4820526c9b2e"
zlib(finalizer): Zlib::GzipWriter object must be closed explicitly.
zlib(finalizer): the stream state was inconsistent.
```

**Comment by repeatedly** [comment]
The root cause is buffer/zlib combination on fluentd side: https://github.com/fluent/fluentd/issues/1903
In `s3`, using `gzip_command` should avoid this problem.

**Comment by mochizuki-masao** [comment]
Thanks! I will try this and report if `gzip_command` works.

**Comment by repeatedly** [comment]
Maybe, latest fluentd has already fixied this issue.
