### ISSUE TITLE
gzip_ command Fallback to Gzipwriter, status = pid 3134 SIGKILL (signal 9)

### ISSUE THREAD

**Issue by fantajeon** [fluent/fluent-plugin-s3#224]
Please help me!!
I'm monitoring cpu utillization and i/o wait. sometimes cpu is 100%, and i/o wait 100%.
I make my docker images from "fluent/fluentd:v1.0-debian-onbuild".
I installed fluent-plugin-s3 -v 1.1.1 --no-document.

This is my conf(for s3):
``` bashshell
199 <label @gogcm_readstream>
200     <match fluent.update>
201         @type null
202     </match>
203     <match **>
204         @type s3
205
206         aws_key_id ********
207         aws_sec_key **************************
208         s3_bucket **************************
209         s3_region a**************************
210         s3_object_key_format %{path}%{time_slice}_%{index}_%{hex_random}.%{file_extension}
211         path logs_gogcm/%Y/%m/%d/
212         store_as gzip_command
213         check_object false
214         ssl_verify_peer false
215
216         <buffer>
217             chunk_limit_size 50K
218             total_limit_size 100M
219             flush_thread_count 8
220             timekey 10m # 6 min partition
221             timekey_wait    1m
222             timekey_use_utc true # use utc
223         </buffer>
224         <format>
225             @type json
226         </format>
227     </match>
228 </label>
```

However, I checked my logs as following:

2018-02-28 01:21:30 +0000 [info]: #0 [echo] listening port port=24720 bind="0.0.0.0"
2018-02-28 01:21:30 +0000 [info]: #0 [search] listening port port=24230 bind="0.0.0.0"
2018-02-28 01:21:30 +0000 [info]: #0 [gsearch] listening port port=24229 bind="0.0.0.0"
2018-02-28 01:21:30 +0000 [info]: #0 [myapns] listening port port=24228 bind="0.0.0.0"
2018-02-28 01:21:30 +0000 [info]: #0 [gogcm] listening port port=24227 bind="0.0.0.0"
2018-02-28 01:21:30 +0000 [info]: #0 [system_read] listening port port=24220 bind="0.0.0.0"
2018-02-28 01:21:30 +0000 [info]: #0 [jirasi] listening port port=24226 bind="0.0.0.0"
2018-02-28 01:21:30 +0000 [info]: #0 [ec3] listening port port=24225 bind="0.0.0.0"
2018-02-28 01:21:30 +0000 [info]: #0 [ec2] listening port port=24224 bind="0.0.0.0"
2018-02-28 01:21:30 +0000 [info]: #0 fluentd worker is now running worker=0
2018-02-28 01:22:39 +0000 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=21.593082011997467 slow_flush_log_threshold=20.0 plugin_id="object:3fac18a48af4"
2018-02-28 01:22:46 +0000 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=27.183080222996068 slow_flush_log_threshold=20.0 plugin_id="object:3fac18a48af4"
2018-02-28 01:22:54 +0000 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=28.14369980400079 slow_flush_log_threshold=20.0 plugin_id="object:3fac18a48af4"
2018-02-28 01:22:56 +0000 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=32.01922203600407 slow_flush_log_threshold=20.0 plugin_id="object:3fac18a48af4"
2018-02-28 01:22:59 +0000 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=26.947401016004733 slow_flush_log_threshold=20.0 plugin_id="object:3fac18a48af4"
2018-02-28 01:23:23 +0000 [warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=44.66891663899878 slow_flush_log_threshold=20.0 plugin_id="object:3fac18a48af4"
2018-02-28 01:25:18 +0000 [warn]: #0 **failed to execute gzip command. Fallback to GzipWriter. status = pid 3134 SIGKILL (signal 9)**
2018-02-28 01:25:59 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-02-28 01:26:00 +0000 chunk="5663b9448334a4684e285d23e2531859" error_class=IOError error="closed stream"
  2018-02-28 01:26:09 +0000 [warn]: #0 /usr/lib/ruby/2.3.0/delegate.rb:341:in `rewind'
  2018-02-28 01:26:09 +0000 [warn]: #0 /usr/lib/ruby/2.3.0/delegate.rb:341:in `block in delegating_block'
  2018-02-28 01:26:09 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-s3-1.1.1/lib/fluent/plugin/out_s3.rb:289:in `write'
  2018-02-28 01:26:09 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:1093:in `try_flush'
  2018-02-28 01:26:09 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:1318:in `flush_thread_run'
  2018-02-28 01:26:09 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:439:in `block (2 levels) in start'
  2018-02-28 01:26:09 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2018-02-28 01:29:40 +0000 [info]: Worker 0 finished unexpectedly with signal SIGKILL
2018-02-28 01:29:51 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '2.6.0'
2018-02-28 01:29:51 +0000 [info]: gem 'fluent-plugin-s3' version '1.1.1'
2018-02-28 01:29:51 +0000 [info]: gem 'fluentd' version '1.0.2'

**Comment by repeatedly** [comment]
Hmm... the reason is sigkill. So someone kills gzip command. Does system monitors process and kill it?
