### ISSUE TITLE
fluent-plugin-s3 won't work if internet connection not available on starting of application

### ISSUE THREAD

**Issue by edgegoldberg** [fluent/fluent-plugin-s3#231]
Hi,
Thank you all for the efforts.
I've noticed a bug recently which I want to  let you know.

**What I want**

    fluent-plugin-s3 keeps working (flushing to S3) without stop 

**What I am currently experiencing**

    fluentd application (configuration) wont work at all and goes to endless loop just to start 

**What I've noticed**

- If internet not available at start of application, application goes to endless loop and continuously try to start. Application have a tail Input Plugin too. The tail input plugin is watching latest (server) log lines. The fluent-plugin-s3 buffers the chunks and flushes based on the configuration. Nothing is working since the application wont even start if internet is not available at start of application.
- If internet is available in between or at start of the application everything works fine.
- If internet drops suddenly when application was started fine and flush time occur then the flush gives warnings (which is obvious) but other things are working fine.

**Environment**

    armv7l GNU/Linux
    Debian GNU/Linux 9.4 (stretch)
    fluentd v1.2.0 (installed by rubygem)
    fluent-plugin-s3 v1.1.3 (installed by rubygem)
    ruby="2.3.3"

**fluentd application (configuration)**

    <source>
      @type tail
      format json
      path /root/ServerLogs/server.log
      pos_file /root/Fluent/logs/server.log.pos
      tag log
    </source>

    <match log.**>
      @type s3
      aws_key_id xxxxxx
      aws_sec_key xxxxxx
      s3_region xxxxxx
      s3_bucket xxxxxx
      path LOG/
      store_as text
      <buffer tag, time>
        retry_type exponential_backoff
        retry_forever true
        @type file
        path /root/Fluent/logs
        timekey 720m #12 hour partition
        timekey_wait 1m
      </buffer>
      <format> 
        @type json
      </format> 
    </match>

**Error on console**

    2018-05-24 15:12:02 +0530 [info]: parsing config file is succeeded path="fluent-test.conf"
    2018-05-24 15:12:08 +0530 [info]: Oj is not installed, and failing back to Yajl for json parser
    2018-05-24 15:12:09 +0530 [info]: Oj is not installed, and failing back to Yajl for json parser
    2018-05-24 15:12:09 +0530 [info]: Oj is not installed, and failing back to Yajl for json parser
    2018-05-24 15:12:09 +0530 [info]: using configuration file: <ROOT>
      <source>
        @type tail
        format json
        path "/root/ServerLogs/server.log"
        pos_file "/root/Fluent/logs/server.log.pos"
        tag "log"
        <parse>
          @type json
        </parse>
      </source>
      <match log.**>
        @type s3
        aws_key_id xxxxxx
        aws_sec_key xxxxxx
        s3_region xxxxxx
        s3_bucket xxxxxx
        path LOG/
        store_as "text"
        <buffer tag, time>
          retry_type exponential_backoff
          retry_forever true
          @type "file"
          path "/root/Fluent/logs"
          timekey 360m
          timekey_wait 1m
        </buffer>
        <format>
          @type "json"
        </format>
      </match>
    </ROOT>
    2018-05-24 15:12:09 +0530 [info]: starting fluentd-1.2.0 pid=29771 ruby="2.3.3"
    2018-05-24 15:12:09 +0530 [info]: spawn command to main:  cmdline=["/usr/bin/ruby2.3", "-Eascii-8bit:ascii-8bit", "/usr/local/bin/fluentd", "-c", "fluent-test.conf", "--under-supervisor"]
    2018-05-24 15:12:15 +0530 [info]: gem 'fluent-plugin-kinesis' version '2.1.1'
    2018-05-24 15:12:15 +0530 [info]: gem 'fluent-plugin-s3' version '1.1.3'
    2018-05-24 15:12:15 +0530 [info]: gem 'fluentd' version '1.2.0'
    2018-05-24 15:12:15 +0530 [info]: adding match pattern="log.**" type="s3"
    2018-05-24 15:12:19 +0530 [info]: adding match pattern="debug.**" type="kinesis_streams_aggregated"
    2018-05-24 15:12:20 +0530 [info]: adding source type="tail"
    2018-05-24 15:12:20 +0530 [info]: #0 Oj is not installed, and failing back to Yajl for json parser
    2018-05-24 15:12:20 +0530 [info]: #0 Oj is not installed, and failing back to Yajl for json parser
    2018-05-24 15:12:20 +0530 [info]: adding source type="http"
    2018-05-24 15:12:20 +0530 [info]: #0 Oj is not installed, and failing back to Yajl for json parser
    2018-05-24 15:12:20 +0530 [info]: #0 starting fluentd worker pid=29953 ppid=29771 worker=0
     2018-05-24 15:13:43 +0530 [error]: #0 unexpected error error_class=RuntimeError error="can't call S3 API. Please check your credentials or s3_region configuration. error = #<Seahorse::Client::NetworkingError: execution expired>"
      2018-05-24 15:13:43 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluent-plugin-s3-1.1.3/lib/fluent/plugin/out_s3.rb:405:in `rescue in check_apikeys'
      2018-05-24 15:13:43 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluent-plugin-s3-1.1.3/lib/fluent/plugin/out_s3.rb:401:in `check_apikeys'
      2018-05-24 15:13:43 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluent-plugin-s3-1.1.3/lib/fluent/plugin/out_s3.rb:215:in `start'
      2018-05-24 15:13:43 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:165:in `block in start'
      2018-05-24 15:13:43 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:154:in `block (2 levels) in lifecycle'
      2018-05-24 15:13:43 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:153:in `each'
      2018-05-24 15:13:43 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:153:in `block in lifecycle'
      2018-05-24 15:13:43 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:140:in `each'
      2018-05-24 15:13:43 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:140:in `lifecycle'
      2018-05-24 15:13:43 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:164:in `start'
      2018-05-24 15:13:43 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/engine.rb:274:in `start'
      2018-05-24 15:13:43 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/engine.rb:219:in `run'
      2018-05-24 15:13:43 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/supervisor.rb:799:in `run_engine'
      2018-05-24 15:13:43 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/supervisor.rb:549:in `block in run_worker'
      2018-05-24 15:13:43 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/supervisor.rb:724:in `main_process'
      2018-05-24 15:13:43 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/supervisor.rb:544:in `run_worker'
      2018-05-24 15:13:43 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
      2018-05-24 15:13:43 +0530 [error]: #0 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      2018-05-24 15:13:43 +0530 [error]: #0 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      2018-05-24 15:13:43 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/bin/fluentd:8:in `<top (required)>'
      2018-05-24 15:13:43 +0530 [error]: #0 /usr/local/bin/fluentd:22:in `load'
      2018-05-24 15:13:43 +0530 [error]: #0 /usr/local/bin/fluentd:22:in `<main>'
    2018-05-24 15:13:43 +0530 [error]: #0 unexpected error error_class=RuntimeError error="can't call S3 API. Please check your credentials or s3_region configuration. error = #<Seahorse::Client::NetworkingError: execution expired>"
      2018-05-24 15:13:43 +0530 [error]: #0 suppressed same stacktrace
    2018-05-24 15:13:43 +0530 [info]: Worker 0 finished unexpectedly with status 1
    2018-05-24 15:13:49 +0530 [info]: gem 'fluent-plugin-kinesis' version '2.1.1'
    2018-05-24 15:13:49 +0530 [info]: gem 'fluent-plugin-s3' version '1.1.3'
    2018-05-24 15:13:49 +0530 [info]: gem 'fluentd' version '1.2.0'
    2018-05-24 15:13:49 +0530 [info]: adding match pattern="log.**" type="s3"
    2018-05-24 15:13:54 +0530 [info]: adding match pattern="debug.**" type="kinesis_streams_aggregated"
    2018-05-24 15:13:54 +0530 [info]: adding source type="tail"
    2018-05-24 15:13:54 +0530 [info]: #0 Oj is not installed, and failing back to Yajl for json parser
    2018-05-24 15:13:54 +0530 [info]: #0 Oj is not installed, and failing back to Yajl for json parser
    2018-05-24 15:13:54 +0530 [info]: adding source type="http"
    2018-05-24 15:13:54 +0530 [info]: #0 Oj is not installed, and failing back to Yajl for json parser
    2018-05-24 15:13:54 +0530 [info]: #0 starting fluentd worker pid=31608 ppid=29771 worker=0
    2018-05-24 15:15:17 +0530 [error]: #0 unexpected error error_class=RuntimeError error="can't call S3 API. Please check your credentials or s3_region configuration. error = #<Seahorse::Client::NetworkingError: execution expired>"
      2018-05-24 15:15:17 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluent-plugin-s3-1.1.3/lib/fluent/plugin/out_s3.rb:405:in `rescue in check_apikeys'
      2018-05-24 15:15:17 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluent-plugin-s3-1.1.3/lib/fluent/plugin/out_s3.rb:401:in `check_apikeys'
      2018-05-24 15:15:17 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluent-plugin-s3-1.1.3/lib/fluent/plugin/out_s3.rb:215:in `start'
      2018-05-24 15:15:17 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:165:in `block in start'
      2018-05-24 15:15:17 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:154:in `block (2 levels) in lifecycle'
      2018-05-24 15:15:17 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:153:in `each'
      2018-05-24 15:15:17 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:153:in `block in lifecycle'
      2018-05-24 15:15:17 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:140:in `each'
      2018-05-24 15:15:17 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:140:in `lifecycle'
      2018-05-24 15:15:17 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:164:in `start'
      2018-05-24 15:15:17 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/engine.rb:274:in `start'
      2018-05-24 15:15:17 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/engine.rb:219:in `run'
      2018-05-24 15:15:17 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/supervisor.rb:799:in `run_engine'
      2018-05-24 15:15:17 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/supervisor.rb:549:in `block in run_worker'
      2018-05-24 15:15:17 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/supervisor.rb:724:in `main_process'
      2018-05-24 15:15:17 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/supervisor.rb:544:in `run_worker'
      2018-05-24 15:15:17 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
      2018-05-24 15:15:17 +0530 [error]: #0 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      2018-05-24 15:15:17 +0530 [error]: #0 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      2018-05-24 15:15:17 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/bin/fluentd:8:in `<top (required)>'
      2018-05-24 15:15:17 +0530 [error]: #0 /usr/local/bin/fluentd:22:in `load'
      2018-05-24 15:15:17 +0530 [error]: #0 /usr/local/bin/fluentd:22:in `<main>'
    2018-05-24 15:15:17 +0530 [error]: #0 unexpected error error_class=RuntimeError error="can't call S3 API. Please check your credentials or s3_region configuration. error = #<Seahorse::Client::NetworkingError: execution expired>"
      2018-05-24 15:15:17 +0530 [error]: #0 suppressed same stacktrace
    2018-05-24 15:15:17 +0530 [info]: Worker 0 finished unexpectedly with status 1

**Comment by repeatedly** [comment]
This is not a bug.
if you want to skip apikey check at start, set `check_apikey_on_start` to `false`.

**Comment by edgegoldberg** [comment]
I just want to mention that access key and secret key are correct. Same fluentd application (configuration) works fine if internet is available on start up of fluent application. 
It wont work only if internet not available on start up.

After setting `check_apikey_on_start` to `false` now I am getting following error

    2018-05-24 18:10:45 +0530 [error]: #0 unexpected error error_class=Seahorse::Client::NetworkingError error="execution expired"
      2018-05-24 18:10:45 +0530 [error]: #0 /usr/lib/ruby/2.3.0/net/http.rb:880:in `initialize'
      2018-05-24 18:10:45 +0530 [error]: #0 /usr/lib/ruby/2.3.0/net/http.rb:880:in `open'
      2018-05-24 18:10:45 +0530 [error]: #0 /usr/lib/ruby/2.3.0/net/http.rb:880:in `block in connect'
      2018-05-24 18:10:45 +0530 [error]: #0 /usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
      2018-05-24 18:10:45 +0530 [error]: #0 /usr/lib/ruby/2.3.0/net/http.rb:878:in `connect'
      2018-05-24 18:10:45 +0530 [error]: #0 /usr/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
      2018-05-24 18:10:45 +0530 [error]: #0 /usr/lib/ruby/2.3.0/net/http.rb:858:in `start'
      2018-05-24 18:10:45 +0530 [error]: #0 /usr/lib/ruby/2.3.0/delegate.rb:83:in `method_missing'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/seahorse/client/net_http/connection_pool.rb:288:in `start_session'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/seahorse/client/net_http/connection_pool.rb:95:in `session_for'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/seahorse/client/net_http/handler.rb:121:in `session'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/seahorse/client/net_http/handler.rb:73:in `transmit'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/seahorse/client/net_http/handler.rb:47:in `call'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/seahorse/client/plugins/content_length.rb:12:in `call'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-s3-1.10.0/lib/aws-sdk-s3/plugins/s3_signer.rb:109:in `call'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-s3-1.10.0/lib/aws-sdk-s3/plugins/s3_signer.rb:57:in `call'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-s3-1.10.0/lib/aws-sdk-s3/plugins/s3_host_id.rb:15:in `call'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/aws-sdk-core/xml/error_handler.rb:8:in `call'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:10:in `call'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-s3-1.10.0/lib/aws-sdk-s3/plugins/s3_signer.rb:87:in `call'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-s3-1.10.0/lib/aws-sdk-s3/plugins/redirects.rb:18:in `call'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/aws-sdk-core/plugins/retry_errors.rb:92:in `call'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/aws-sdk-core/plugins/retry_errors.rb:123:in `retry_request'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/aws-sdk-core/plugins/retry_errors.rb:106:in `retry_if_possible'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/aws-sdk-core/plugins/retry_errors.rb:94:in `call'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/aws-sdk-core/plugins/retry_errors.rb:123:in `retry_request'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/aws-sdk-core/plugins/retry_errors.rb:106:in `retry_if_possible'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/aws-sdk-core/plugins/retry_errors.rb:94:in `call'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/aws-sdk-core/plugins/retry_errors.rb:123:in `retry_request'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/aws-sdk-core/plugins/retry_errors.rb:106:in `retry_if_possible'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/aws-sdk-core/plugins/retry_errors.rb:94:in `call'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-s3-1.10.0/lib/aws-sdk-s3/plugins/dualstack.rb:34:in `call'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-s3-1.10.0/lib/aws-sdk-s3/plugins/accelerate.rb:50:in `call'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-s3-1.10.0/lib/aws-sdk-s3/plugins/md5s.rb:28:in `call'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-s3-1.10.0/lib/aws-sdk-s3/plugins/bucket_name_restrictions.rb:13:in `call'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-s3-1.10.0/lib/aws-sdk-s3/plugins/expect_100_continue.rb:22:in `call'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-s3-1.10.0/lib/aws-sdk-s3/plugins/bucket_dns.rb:33:in `call'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/aws-sdk-core/rest/handler.rb:8:in `call'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/aws-sdk-core/plugins/user_agent.rb:13:in `call'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/seahorse/client/plugins/endpoint.rb:45:in `call'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/aws-sdk-core/plugins/param_validator.rb:24:in `call'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-s3-1.10.0/lib/aws-sdk-s3/plugins/sse_cpk.rb:22:in `call'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-s3-1.10.0/lib/aws-sdk-s3/plugins/dualstack.rb:26:in `call'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-s3-1.10.0/lib/aws-sdk-s3/plugins/accelerate.rb:35:in `call'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/seahorse/client/plugins/response_target.rb:23:in `call'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/seahorse/client/request.rb:70:in `send_request'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/aws-sdk-core/waiters/poller.rb:63:in `send_request'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/aws-sdk-core/waiters/poller.rb:49:in `call'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/aws-sdk-core/waiters/waiter.rb:105:in `block in poll'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/aws-sdk-core/waiters/waiter.rb:102:in `loop'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/aws-sdk-core/waiters/waiter.rb:102:in `poll'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/aws-sdk-core/waiters/waiter.rb:92:in `block (2 levels) in wait'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/aws-sdk-core/waiters/waiter.rb:91:in `catch'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/aws-sdk-core/waiters/waiter.rb:91:in `block in wait'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/aws-sdk-core/waiters/waiter.rb:90:in `catch'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-core-3.20.2/lib/aws-sdk-core/waiters/waiter.rb:90:in `wait'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-s3-1.10.0/lib/aws-sdk-s3/waiters.rb:57:in `wait'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-s3-1.10.0/lib/aws-sdk-s3/bucket.rb:93:in `wait_until_exists'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/aws-sdk-s3-1.10.0/lib/aws-sdk-s3/bucket.rb:74:in `exists?'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluent-plugin-s3-1.1.3/lib/fluent/plugin/out_s3.rb:362:in `ensure_bucket'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluent-plugin-s3-1.1.3/lib/fluent/plugin/out_s3.rb:216:in `start'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:165:in `block in start'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:154:in `block (2 levels) in lifecycle'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:153:in `each'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:153:in `block in lifecycle'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:140:in `each'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:140:in `lifecycle'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:164:in `start'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/engine.rb:274:in `start'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/engine.rb:219:in `run'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/supervisor.rb:799:in `run_engine'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/supervisor.rb:549:in `block in run_worker'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/supervisor.rb:724:in `main_process'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/supervisor.rb:544:in `run_worker'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
      2018-05-24 18:10:45 +0530 [error]: #0 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      2018-05-24 18:10:45 +0530 [error]: #0 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
      2018-05-24 18:10:45 +0530 [error]: #0 /root/.gem/ruby/2.3.0/gems/fluentd-1.2.0/bin/fluentd:8:in `<top (required)>'
      2018-05-24 18:10:45 +0530 [error]: #0 /usr/local/bin/fluentd:22:in `load'
      2018-05-24 18:10:45 +0530 [error]: #0 /usr/local/bin/fluentd:22:in `<main>'
    2018-05-24 18:10:45 +0530 [error]: #0 unexpected error error_class=Seahorse::Client::NetworkingError error="execution expired"
      2018-05-24 18:10:45 +0530 [error]: #0 suppressed same stacktrace
