### ISSUE TITLE
error_class=Seahorse::Client::NetworkingError error="execution expired" when Using s3-Input plugin

### ISSUE THREAD

**Issue by lel085** [fluent/fluent-plugin-s3#245]
I am trying to use the s3-input plugin for reading data as per the document.
but, I am getting below error
2018-10-08 16:38:14 +0000 [error]: #0 unexpected error error_class=Seahorse::Client::NetworkingError error="execution expired"
@okkez Can you please say why this errors? Any solution to fix the issue?
I used below config for s3 _input 

```aconf
 < source >
   @type s3
   s3_bucket ******-dev-us-east-1
   s3_region us-east-1
  < sqs >
    queue_name ****-queue
  </ sqs >
</ source >
```

Here is the Logs:

```log
2018-10-09 01:25:23 +0000 [error]: #0 unexpected error error_class=Seahorse::Client::NetworkingError error="execution expired"
  2018-10-09 01:25:23 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/2.4.0/net/http.rb:904:in `initialize'
  2018-10-09 01:25:23 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/2.4.0/net/http.rb:904:in `open'
  2018-10-09 01:25:23 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/2.4.0/net/http.rb:904:in `block in connect'
  2018-10-09 01:25:23 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
  2018-10-09 01:25:23 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/2.4.0/net/http.rb:902:in `connect'
  2018-10-09 01:25:23 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
  2018-10-09 01:25:23 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/2.4.0/net/http.rb:882:in `start'
  2018-10-09 01:25:23 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/2.4.0/delegate.rb:83:in `method_missing'
  2018-10-09 01:25:23 +0000 [error]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/aws-sdk-core-3.28.0/lib/seahorse/client/net_http/connection_pool.rb:297:in `start_session'
```

**Comment by jayhding** [comment]
Seems as #240 and I have met same problem.

**Comment by kenhys** [comment]
It seems that duplicate of #240
