### ISSUE TITLE
Fluentd on EKS: MissingCredentialsError when expecting it to use instance profile creds

### ISSUE THREAD

**Issue by cwhatley** [fluent/fluent-plugin-s3#268]
I am using fluent/fluentd-kubernetes-daemonset:v1.3-debian-s3 in a daemonset and properly setting S3_BUCKET_NAME and S3_BUCKET_REGION, but it seems to be choking on trying to get credentials from the instance profile.

Any idea what's the cause? 

Errors below:

2019-03-14 01:18:04 +0000 [error]: #0 unexpected error error_class=Aws::Sigv4::Errors::MissingCredentialsError error="missing credentials, provide credentials with one of the following options:\n  - :access_key_id and :secret_access_key\n  - :credentials\n  - :credentials_provider"
  2019-03-14 01:18:04 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/aws-sigv4-1.0.3/lib/aws-sigv4/signer.rb:517:in `extract_credentials_provider'
  2019-03-14 01:18:04 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/aws-sigv4-1.0.3/lib/aws-sigv4/signer.rb:121:in `initialize'
  2019-03-14 01:18:04 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/aws-sdk-s3-1.30.1/lib/aws-sdk-s3/plugins/s3_signer.rb:190:in `new'
  2019-03-14 01:18:04 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/aws-sdk-s3-1.30.1/lib/aws-sdk-s3/plugins/s3_signer.rb:190:in `build_v4_signer'
  2019-03-14 01:18:04 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/aws-sdk-s3-1.30.1/lib/aws-sdk-s3/plugins/s3_signer.rb:13:in `block in <class:S3Signer>'
  2019-03-14 01:18:04 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-3.46.1/lib/seahorse/client/configuration.rb:70:in `call'
  2019-03-14 01:18:04 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-3.46.1/lib/seahorse/client/configuration.rb:213:in `block in resolve_defaults'
  2019-03-14 01:18:04 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-3.46.1/lib/seahorse/client/configuration.rb:57:in `each'
  2019-03-14 01:18:04 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-3.46.1/lib/seahorse/client/configuration.rb:57:in `each'
  2019-03-14 01:18:04 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-3.46.1/lib/seahorse/client/configuration.rb:212:in `resolve_defaults'
  2019-03-14 01:18:04 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-3.46.1/lib/seahorse/client/configuration.rb:205:in `value_at'
  2019-03-14 01:18:04 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/aws-sdk-core-3.46.1/lib/seahorse/client/configuration.rb:189:in `block in resolve'

**Comment by cwhatley** [comment]
I explicitly added the instance_profile_credentials to the block and now it is working. Should that be required? The docs seem to say that you can have only the bucket and region and it should work.

**Comment by Ramneekkhurana** [comment]
@cwhatley , where are you able to see these logs, i am facing a similar issue but can't see anything in the fluend container logs

**Comment by rmccarthy-ellevation** [comment]
@cwhatley @Ramneekkhurana  I have this working on a linux aws instance with an instance profile that allows access to the bucket, however, when I tried this on Windows I get the same error. Nothing mentioned in the documentation about there being a difference. If anyone has figured it out please let me know. Thanks.

**Comment by pinkavaj** [comment]
It was necessary to disable `containerSecurityContext` to make it working.
