### ISSUE TITLE
Missing permission regarding SSE?

### ISSUE THREAD

**Issue by Jonnymcc** [fluent/fluent-plugin-s3#272]
Using the IAM policy specified in the README with GetObject, PutObject, and LIstBucket.

```
2019-04-25 12:14:52 -0400 [warn]: temporarily failed to flush the buffer. next_retry=2019-04-25 12:14:52 -0400 error_class="Aws::S3::Errors::AccessDenied" error="Access Denied" plugin_id="object:3fd9915538e0"
2019-04-25 12:14:52 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.6.42/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
2019-04-25 12:14:52 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.6.42/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:19:in `call'
2019-04-25 12:14:52 -0400 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.6.42/lib/aws-sdk-core/plugins/s3_dualstack.rb:24:in `call'
```

**Comment by repeatedly** [comment]
Do you mean your configuration works whithout SSE parameters?

**Comment by Jonnymcc** [comment]
I have no SSE config set, yet it fails to flush to S3.

```
td-agent.x86_64                                                         2.3.4-1.el2016

2019-04-25 13:48:59 -0400 [info]: gem 'fluent-mixin-config-placeholders' version '0.4.0'
2019-04-25 13:48:59 -0400 [info]: gem 'fluent-mixin-plaintextformatter' version '0.2.6'
2019-04-25 13:48:59 -0400 [info]: gem 'fluent-plugin-kafka' version '0.4.1'
2019-04-25 13:48:59 -0400 [info]: gem 'fluent-plugin-mongo' version '0.7.16'
2019-04-25 13:48:59 -0400 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '1.5.5'
2019-04-25 13:48:59 -0400 [info]: gem 'fluent-plugin-s3' version '1.1.9'
2019-04-25 13:48:59 -0400 [info]: gem 'fluent-plugin-s3' version '0.8.0'
2019-04-25 13:48:59 -0400 [info]: gem 'fluent-plugin-scribe' version '0.10.14'
2019-04-25 13:48:59 -0400 [info]: gem 'fluent-plugin-td' version '0.10.29'
2019-04-25 13:48:59 -0400 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.2'
2019-04-25 13:48:59 -0400 [info]: gem 'fluent-plugin-webhdfs' version '0.4.2'
2019-04-25 13:48:59 -0400 [info]: gem 'fluentd' version '1.4.2'
2019-04-25 13:48:59 -0400 [info]: gem 'fluentd' version '0.12.31'
```

**Comment by Jonnymcc** [comment]
I think I had a leading / in my key path which was causing the issue, works now.
