### ISSUE TITLE
Aws S3 Forbidden during object check even with full bucket permissions

### ISSUE THREAD

**Issue by gumho** [fluent/fluent-plugin-s3#300]
We see the following error when trying to output to an S3 bucket where FULL permissions are granted to the instance profile used by the Fluentd s3 plugin:

```
2019-11-06 18:58:39 +0000 [debug]: #0 taking back chunk for errors. chunk="5968e5649a7db87a2c943e107862d65d"
2019-11-06 18:58:39 +0000 [warn]: #0 failed to flush the buffer. retry_time=1 next_retry_seconds=2019-11-06 18:58:40 +0000 chunk="5968e5649a7db87a2c943e107862d65d" error_class=Aws::S3::Errors::Forbidden error=""
  2019-11-06 18:58:39 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/aws-sdk-s3-1.45.0/lib/aws-sdk-s3/object.rb:283:in `rescue in exists?'
  2019-11-06 18:58:39 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/aws-sdk-s3-1.45.0/lib/aws-sdk-s3/object.rb:279:in `exists?'
  2019-11-06 18:58:39 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluent-plugin-s3-1.1.11/lib/fluent/plugin/out_s3.rb:270:in `write'
  2019-11-06 18:58:39 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.4.2/lib/fluent/plugin/output.rb:1125:in `try_flush'
  2019-11-06 18:58:39 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.4.2/lib/fluent/plugin/output.rb:1425:in `flush_thread_run'
  2019-11-06 18:58:39 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.4.2/lib/fluent/plugin/output.rb:454:in `block (2 levels) in start'
  2019-11-06 18:58:39 +0000 [warn]: #0 /var/lib/gems/2.3.0/gems/fluentd-1.4.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```
Our config looks like this:

```
<match **>
    @type s3
    @log_level debug

    s3_bucket xxxxx
    s3_region xxxxx

    <instance_profile_credentials>
    </instance_profile_credentials>

    path "xxxxx" 

    acl bucket-owner-full-control

    include_time_key
    time_key "@timestamp"

    num_threads 4
    buffer_type    file
    buffer_path    xxxxx.log
    flush_interval 5s
    buffer_chunk_limit 1m

    time_slice_format %Y%m%d%H
    time_slice_wait 5m
    utc
    format json
</match>
```

I have seen threads such as https://groups.google.com/forum/#!topic/fluentd/Vvok7FTVuq4 and https://github.com/aws/aws-sdk-ruby/issues/201#issuecomment-288908134 mention that finer privileges are needed (as opposed to granting `s3:*`) but that did not seem to fix the issue.

The only workaround that works is to completely disable object_check by setting `object_check false`.

**Comment by srirachapills** [comment]
How does your IAM role policy looks like?
