### ISSUE TITLE
Retry exponential backoff does not work with invalid/expired configuration

### ISSUE THREAD

**Issue by ventsislav-georgiev** [fluent/fluent-plugin-s3#359]
#### Problem
Setting invalid configuration for example key id, fails the plugin with the following error:
```
2020-11-30 17:02:07 +0000 [error]: #0 unexpected error error_class=RuntimeError error="can't call S3 API. Please check your credentials or s3_region configuration. error = #<Aws::S3::Errors::InvalidAccess 
2020-11-30 17:02:07 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-s3-1.4.0/lib/fluent/plugin/out_s3.rb:469:in `rescue in check_apikeys'
2020-11-30 17:02:07 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-s3-1.4.0/lib/fluent/plugin/out_s3.rb:464:in `check_apikeys'
2020-11-30 17:02:07 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluent-plugin-s3-1.4.0/lib/fluent/plugin/out_s3.rb:254:in `start'
2020-11-30 17:02:07 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/root_agent.rb:200:in `block in start'
2020-11-30 17:02:07 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/root_agent.rb:189:in `block (2 levels) in lifecycle'
2020-11-30 17:02:07 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/root_agent.rb:188:in `each'
2020-11-30 17:02:07 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/root_agent.rb:188:in `block in lifecycle'
2020-11-30 17:02:07 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/root_agent.rb:175:in `each'
2020-11-30 17:02:07 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/root_agent.rb:175:in `lifecycle'
2020-11-30 17:02:07 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/root_agent.rb:199:in `start'
2020-11-30 17:02:07 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/engine.rb:248:in `start'
2020-11-30 17:02:07 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/engine.rb:147:in `run'
2020-11-30 17:02:07 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/supervisor.rb:603:in `block in run_worker'
2020-11-30 17:02:07 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/supervisor.rb:840:in `main_process'
2020-11-30 17:02:07 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/supervisor.rb:594:in `run_worker'
2020-11-30 17:02:07 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/lib/fluent/command/fluentd.rb:361:in `<top (required)>' 
2020-11-30 17:02:07 +0000 [error]: #0 /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
2020-11-30 17:02:07 +0000 [error]: #0 /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
2020-11-30 17:02:07 +0000 [error]: #0 /usr/lib/ruby/gems/2.5.0/gems/fluentd-1.11.2/bin/fluentd:8:in `<top (required)>' 
2020-11-30 17:02:07 +0000 [error]: #0 /usr/bin/fluentd:23:in `load'
2020-11-30 17:02:07 +0000 [error]: #0 /usr/bin/fluentd:23:in `<main>'
```

<br/>
<br/>

This error repeats every 11-12 seconds (may depend on the flush interval) and the process is constantly working instead of properly applying the configured retry exponential backoff.

Buffer configuration:
```
<buffer>
  @type file
  path /fluentd/tmp/buffers
  flush_mode interval
  flush_interval 5s
  overflow_action block
  retry_type exponential_backoff
  retry_forever true
  retry_max_interval 5m
</buffer>
```

#### Steps to replicate
```
<match *>
  @type s3
  s3_object_key_format '%{path}/%Y/%m/%d/%H/%H-%M-%S_%{uuid_flush}.%{file_extension}'
  s3_bucket 'test'
  aws_key_id 'test'
  aws_sec_key 'test'
  <buffer tag,time>
    @type file
    path /fluentd/tmp/buffers
    timekey 5s
    timekey_use_utc true
    overflow_action block
    retry_type exponential_backoff
    retry_forever true
    retry_max_interval 5m
  </buffer>
</match>
```

#### Expected Behavior or What you need to ask
Plugin catches the above error.. Logs a simple message and retries with exponential backoff.

...

#### Using Fluentd and S3 plugin versions

* OS version macOS Catalina
* Bare Metal/Docker/Kubernetes all the same
* fluentd 1.11.2
* fluent-plugin-s3 (1.4.0)

**Comment by ventsislav-georgiev** [comment]
It appears this issue will be difficult to fix in the plugin. A viable workaround when using Kubernetes, is to use a single output plugin per Fluentd instance and run Fluentd in no supervisor mode. This will make the plugin crash result in a Fluentd crash and be properly handled by Kubernetes, by making the pod entering a CrashLoop with exponential back off retries.
