### ISSUE TITLE
InvalidRegionError error="Invalid `:region` option was provided.\n\n* Not every service is available in every region.

### ISSUE THREAD

**Issue by vinod827** [fluent/fluent-plugin-s3#376]
I'm trying to run the FluentD on my AWS EKS cluster so that I can send the logs generated by certain pods to AWS S3 bucket.
I'm trying to run the FluentD as Kubernetes DaemonSet but keep on getting below error:-

```
2021-06-03 11:06:07 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.12.4/lib/fluent/root_agent.rb:188:in `block in lifecycle'
  2021-06-03 11:06:07 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.12.4/lib/fluent/root_agent.rb:175:in `each'
  2021-06-03 11:06:07 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.12.4/lib/fluent/root_agent.rb:175:in `lifecycle'
  2021-06-03 11:06:07 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.12.4/lib/fluent/root_agent.rb:199:in `start'
  2021-06-03 11:06:07 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.12.4/lib/fluent/engine.rb:248:in `start'
  2021-06-03 11:06:07 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.12.4/lib/fluent/engine.rb:147:in `run'
  2021-06-03 11:06:07 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.12.4/lib/fluent/supervisor.rb:700:in `block in run_worker'
  2021-06-03 11:06:07 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.12.4/lib/fluent/supervisor.rb:951:in `main_process'
  2021-06-03 11:06:07 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.12.4/lib/fluent/supervisor.rb:691:in `run_worker'
  2021-06-03 11:06:07 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.12.4/lib/fluent/command/fluentd.rb:365:in `<top (required)>'
  2021-06-03 11:06:07 +0000 [error]: #0 /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2021-06-03 11:06:07 +0000 [error]: #0 /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2021-06-03 11:06:07 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.12.4/bin/fluentd:8:in `<top (required)>'
  2021-06-03 11:06:07 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/bin/fluentd:23:in `load'
  2021-06-03 11:06:07 +0000 [error]: #0 /fluentd/vendor/bundle/ruby/2.6.0/bin/fluentd:23:in `<main>'
2021-06-03 11:06:07 +0000 [error]: #0 unexpected error error_class=Aws::Errors::InvalidRegionError error="Invalid `:region` option was provided.\n\n* Not every service is available in every region.\n\n* Never suffix region names with availability zones.\n  Use \"us-east-1\", not \"us-east-1a\"\n\nKnown AWS regions include (not specific to this service):\n\naf-south-1\nap-east-1\nap-northeast-1\nap-northeast-2\nap-northeast-3\nap-south-1\nap-southeast-1\nap-southeast-2\nca-central-1\neu-central-1\neu-north-1\neu-south-1\neu-west-1\neu-west-2\neu-west-3\nme-south-1\nsa-east-1\nus-east-1\nus-east-2\nus-west-1\nus-west-2\ncn-north-1\ncn-northwest-1\nus-gov-east-1\nus-gov-west-1\nus-iso-east-1\nus-isob-east-1\n"
  2021-06-03 11:06:07 +0000 [error]: #0 suppressed same stacktrace
2021-06-03 11:06:07 +0000 [info]: Worker 0 finished unexpectedly with status 1
2021-06-03 11:06:08 +0000 [info]: adding match in @FLUENT_LOG pattern="fluent.**" type="null"
2021-06-03 11:06:08 +0000 [info]: adding filter pattern="kubernetes.**" type="kubernetes_metadata"
^C
```

DaemonSet:-

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      name: fluentd-elasticsearch
  template:
    metadata:
      labels:
        name: fluentd-elasticsearch
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.12.4-debian-s3-1.0 # For AWS 3
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: config-volume
          mountPath: /fluentd/etc/k8s-fluentd.conf
          subPath: k8s-fluentd.conf
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config-volume
        configMap:
          name: fluentd-conf
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
```

ConfigMap:-

```
apiVersion: v1
data:
  kubernetes.conf: |-
    <source>
      @type tail
      read_from_head true
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag s3.logs
    </source>

    # Store Data in S3
    <match s3.logs>
      @type s3
      aws_key_id <my AWS Key>
      aws_sec_key <my AWS Secret Access Key>
      s3_bucket test-cis-2
      #s3_region us-east-1
      s3_endpoint s3-us-east-1.amazonaws.com
      path logs/
      # if you want to use ${tag} or %Y/%m/%d/ like syntax in path / s3_object_key_format,
      # need to specify tag for ${tag} and time for %Y/%m/%d in <buffer> argument.
      <buffer tag,time>
        @type file
        path /var/log/fluent/s3
        timekey 3600 # 1 hour partition
        timekey_wait 10m
        timekey_use_utc true # use utc
        chunk_limit_size 256m
      </buffer>
    </match>
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: fluentd-conf
  namespace: kube-system
```

It is throwing error with region name. I tried with region as us-east-1 and then commented it out and keep just s3_endpoint but nothing is working. Please assist, thanks

**Comment by kenhys** [comment]
It seems that error logs indicate the reason. (`us-east-1a` is specified).
Could you check above configuration is correctly applied to the pod?

```
 Not every service is available in every region.\n\n* Never suffix region names with availability zones.\n  Use \"us-east-1\", not \"us-east-1a\"\n\n
```
