### ISSUE TITLE
Plugin not working on basic implementation

### ISSUE THREAD

**Issue by valentinacala** [fluent/fluent-plugin-s3#428]
### Describe the bug

Try to read S3 as input, getting:
` error_class=Aws::S3::Errors::NoSuchKey error="The specified key does not exist."`

### To Reproduce

conf/fluent.conf:
``````
<source>
  @type s3
  aws_key_id xxx
  aws_sec_key xxx
  s3_bucket bucket.uno
  s3_region eu-north-1
  <sqs>
    queue_name sqs-uno
  </sqs>
</source>
<match elk>
    @type copy
    <store>
      @type stdout
    </store>
</match>
``````

Dockerfile:
``````
FROM fluent/fluentd:v1.16.2-debian-1.0
USER root
RUN ["gem", "install", "elasticsearch", "--no-document", "--version", "<8"]
RUN ["gem", "install", "fluent-plugin-elasticsearch", "--no-document", "--version", "5.2.2"]
RUN ["gem", "install", "fluent-plugin-s3", "--no-document", "--version", "1.7.2"]
``````

dockerfile:
``````
version: "3"
services:
  fluentd:
    container_name: fluentd
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
``````
Running locally:
`docker-compose  up -d`

### Expected behavior

I expect files in my s3 instance are read with no errors

### Your Environment

```markdown
- Fluentd version: v1.16.2-debian-1.0
- TD Agent version:
- fluent-plugin-s3 version: 1.7.2
- aws-sdk-s3 version:
- aws-sdk-sqs version:
- Operating system:
- Kernel version:
```

### Your Configuration

see previous section

### Your Error Log

```shell
2023-08-07 14:10:06 +0000 [info]: using configuration file: <ROOT>
  <source>
    @type s3
    aws_key_id xxxxxx
    aws_sec_key xxxxxx
    s3_bucket "bucket.uno"
    s3_region "eu-north-1"
    <sqs>
      queue_name "sqs-uno"
    </sqs>
  </source>
  <filter elk>
    type record_transformer
    enable_ruby 
    <record>
      id_woa ${record['tailed_path'][/\/usr\/share\/mylogs\/(?<myidinpath>[[:word:]]+)/,"myidinpath"]}
      mobile_module ${record['tailed_path'][/\/usr\/share\/mylogs\/[[:word:]]+\/(?<mobilemodule>[[:word:]]+)/,"mobilemodule"]}
    </record>
  </filter>
  <match elk>
    @type copy
    <store>
      @type "stdout"
    </store>
  </match>
</ROOT>
2023-08-07 14:10:06 +0000 [info]: starting fluentd-1.16.2 pid=7 ruby="3.1.4"
2023-08-07 14:10:06 +0000 [info]: spawn command to main:  cmdline=["/usr/local/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/local/bundle/bin/fluentd", "--config", "/fluentd/etc/fluent.conf", "--plugin", "/fluentd/plugins", "--under-supervisor"]
2023-08-07 14:10:06 +0000 [info]: #0 init worker0 logger path=nil rotate_age=nil rotate_size=nil
2023-08-07 14:10:06 +0000 [warn]: #0 'type' is deprecated parameter name. use '@type' instead.
2023-08-07 14:10:06 +0000 [info]: adding filter pattern="elk" type="record_transformer"
2023-08-07 14:10:06 +0000 [warn]: #0 'type' is deprecated parameter name. use '@type' instead.
2023-08-07 14:10:06 +0000 [info]: adding match pattern="elk" type="copy"
2023-08-07 14:10:06 +0000 [info]: adding source type="s3"
2023-08-07 14:10:06 +0000 [info]: #0 starting fluentd worker pid=16 ppid=7 worker=0
2023-08-07 14:10:07 +0000 [info]: #0 fluentd worker is now running worker=0
2023-08-07 14:10:07 +0000 [warn]: #0  error_class=Aws::S3::Errors::NoSuchKey error="The specified key does not exist."
  2023-08-07 14:10:07 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-core-3.180.1/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call'
  2023-08-07 14:10:07 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-s3-1.132.0/lib/aws-sdk-s3/plugins/skip_whole_multipart_get_checksums.rb:18:in `call'
  2023-08-07 14:10:07 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-s3-1.132.0/lib/aws-sdk-s3/plugins/sse_cpk.rb:24:in `call'
  2023-08-07 14:10:07 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-s3-1.132.0/lib/aws-sdk-s3/plugins/dualstack.rb:21:in `call'
  2023-08-07 14:10:07 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-s3-1.132.0/lib/aws-sdk-s3/plugins/accelerate.rb:43:in `call'
  2023-08-07 14:10:07 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-core-3.180.1/lib/aws-sdk-core/plugins/checksum_algorithm.rb:111:in `call'
  2023-08-07 14:10:07 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-core-3.180.1/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:16:in `call'
  2023-08-07 14:10:07 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-core-3.180.1/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
  2023-08-07 14:10:07 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-core-3.180.1/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
  2023-08-07 14:10:07 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-core-3.180.1/lib/seahorse/client/plugins/request_callback.rb:71:in `call'
  2023-08-07 14:10:07 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-core-3.180.1/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
  2023-08-07 14:10:07 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-core-3.180.1/lib/seahorse/client/plugins/response_target.rb:24:in `call'
  2023-08-07 14:10:07 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-core-3.180.1/lib/seahorse/client/request.rb:72:in `send_request'
  2023-08-07 14:10:07 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-s3-1.132.0/lib/aws-sdk-s3/client.rb:6081:in `get_object'
  2023-08-07 14:10:07 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-s3-1.132.0/lib/aws-sdk-s3/object.rb:1006:in `block in get'
  2023-08-07 14:10:07 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-core-3.180.1/lib/aws-sdk-core/plugins/user_agent.rb:28:in `feature'
  2023-08-07 14:10:07 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-s3-1.132.0/lib/aws-sdk-s3/object.rb:1005:in `get'
  2023-08-07 14:10:07 +0000 [warn]: #0 /usr/local/bundle/gems/fluent-plugin-s3-1.7.2/lib/fluent/plugin/in_s3.rb:343:in `process'
  2023-08-07 14:10:07 +0000 [warn]: #0 /usr/local/bundle/gems/fluent-plugin-s3-1.7.2/lib/fluent/plugin/in_s3.rb:216:in `block in run'
  2023-08-07 14:10:07 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-sqs-1.62.0/lib/aws-sdk-sqs/queue_poller.rb:415:in `block in yield_messages'
  2023-08-07 14:10:07 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-sqs-1.62.0/lib/aws-sdk-sqs/queue_poller.rb:414:in `each'
  2023-08-07 14:10:07 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-sqs-1.62.0/lib/aws-sdk-sqs/queue_poller.rb:414:in `yield_messages'
  2023-08-07 14:10:07 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-sqs-1.62.0/lib/aws-sdk-sqs/queue_poller.rb:407:in `block in process_messages'
  2023-08-07 14:10:07 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-sqs-1.62.0/lib/aws-sdk-sqs/queue_poller.rb:406:in `catch'
  2023-08-07 14:10:07 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-sqs-1.62.0/lib/aws-sdk-sqs/queue_poller.rb:406:in `process_messages'
  2023-08-07 14:10:07 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-sqs-1.62.0/lib/aws-sdk-sqs/queue_poller.rb:338:in `block (2 levels) in poll'
  2023-08-07 14:10:07 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-sqs-1.62.0/lib/aws-sdk-sqs/queue_poller.rb:333:in `loop'
  2023-08-07 14:10:07 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-sqs-1.62.0/lib/aws-sdk-sqs/queue_poller.rb:333:in `block in poll'
  2023-08-07 14:10:07 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-sqs-1.62.0/lib/aws-sdk-sqs/queue_poller.rb:332:in `catch'
  2023-08-07 14:10:07 +0000 [warn]: #0 /usr/local/bundle/gems/aws-sdk-sqs-1.62.0/lib/aws-sdk-sqs/queue_poller.rb:332:in `poll'
  2023-08-07 14:10:07 +0000 [warn]: #0 /usr/local/bundle/gems/fluent-plugin-s3-1.7.2/lib/fluent/plugin/in_s3.rb:206:in `run'
  2023-08-07 14:10:07 +0000 [warn]: #0 /usr/local/bundle/gems/fluentd-1.16.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```

**Comment by valentinacala** [comment]
Solution found. It can happen when a file is deleted from the S3 while the creation message exist in the sqs. Cleaning the queue solves the problem

**Comment by valentinacala** [comment]
Solution found. It can happen when a file is deleted from the S3 while the creation message exist in the sqs. Cleaning the queue solves the problem
