### ISSUE TITLE
'auto_create_bucket' does not seem to work.

### ISSUE THREAD

**Issue by masaomoc** [fluent/fluent-plugin-s3#60]
In my Linux server, I installed td-agent 1.1.21 and fluent-plugin-s3-0.4.1 which is installed with td-agent.
My td-agent.conf is like below:
```
<match **>
  type s3
  s3_bucket foobar # this bucket does not exist.
  s3_endpoint s3-ap-northeast-1.amazonaws.com

  path ${tag}/
  time_slice_format %Y%m%d/%H/%M/
  time_slice_wait 1m
  s3_object_key_format %{path}%{time_slice}${hostname}.%{index}.%{file_extension}

  buffer_path /var/log/td-agent/buffer/${tag}
</match>
```
and I expected the S3 bucket to be created because ```auto_create_bucket``` is set default to true. But td-agent raised an error and td-agent.log show below errors:
```
2014-12-05 02:18:40 +0000 [error]: unexpected error error_class=RuntimeError error=#<RuntimeError: aws_key_id or aws_sec_key is invalid. Please check your configuration>
  2014-12-05 02:18:40 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-s3-0.4.1/lib/fluent/plugin/out_s3.rb:190:in `rescue in check_apikeys'
  2014-12-05 02:18:40 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-s3-0.4.1/lib/fluent/plugin/out_s3.rb:188:in `check_apikeys'
  2014-12-05 02:18:40 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-s3-0.4.1/lib/fluent/plugin/out_s3.rb:111:in `start'
  2014-12-05 02:18:40 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/match.rb:40:in `start'
  2014-12-05 02:18:40 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/engine.rb:263:in `block in start'
  2014-12-05 02:18:40 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/engine.rb:262:in `each'
  2014-12-05 02:18:40 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/engine.rb:262:in `start'
  2014-12-05 02:18:40 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/engine.rb:213:in `run'
  2014-12-05 02:18:40 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/supervisor.rb:464:in `run_engine'
  2014-12-05 02:18:40 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/supervisor.rb:135:in `block in start'
  2014-12-05 02:18:40 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/supervisor.rb:250:in `call'
  2014-12-05 02:18:40 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/supervisor.rb:250:in `main_process'
  2014-12-05 02:18:40 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/supervisor.rb:225:in `block in supervise'
  2014-12-05 02:18:40 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/supervisor.rb:224:in `fork'
  2014-12-05 02:18:40 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/supervisor.rb:224:in `supervise'
  2014-12-05 02:18:40 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/supervisor.rb:128:in `start'
  2014-12-05 02:18:40 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/lib/fluent/command/fluentd.rb:164:in `<top (required)>'
  2014-12-05 02:18:40 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
  2014-12-05 02:18:40 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
  2014-12-05 02:18:40 +0000 [error]: /usr/lib64/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.55/bin/fluentd:6:in `<top (required)>'
  2014-12-05 02:18:40 +0000 [error]: /usr/lib64/fluent/ruby/bin/fluentd:23:in `load'
  2014-12-05 02:18:40 +0000 [error]: /usr/lib64/fluent/ruby/bin/fluentd:23:in `<top (required)>'
  2014-12-05 02:18:40 +0000 [error]: /usr/sbin/td-agent:7:in `load'
  2014-12-05 02:18:40 +0000 [error]: /usr/sbin/td-agent:7:in `<main>'
```

I'm runnning this server on EC2 and setting S3Admin IAM Role so apikeys are correct.
I read  out_s3.rb and checked aws-sdk, and it seems that ```bucket.empty?``` in ```check_apikeys``` raises ```AWS::S3::Errors::NoSuchBucket``` when the specified bucket does not exist. Therefore, ```auto_create_bucket``` configuration seems to never be used.

I'll submit Pull requests, but before writing batch, please check if my suspicion is correct.

``` 
$ rpm -qa | grep td-agent
td-agent-1.1.21-0.x86_64
```

**Comment by repeatedly** [comment]
Forgot to close this issue.
