### ISSUE TITLE
Configuration for S3 compatible service

### ISSUE THREAD

**Issue by yhidai** [fluent/fluent-plugin-s3#75]
Would you mind checking s3_endpoint configuration for S3 compatible service ?
I got this error message below  when I tried to transport log files to RiakCS via fluent-s3-plugin.

015-03-30 15:36:45 +0900 [error]: unexpected error error_class=AWS::S3::Errors::InvalidAccessKeyId error=#<AWS::S3::Errors::InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.>
2015-03-30 15:36:45 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.63.0/lib/aws/core/client.rb:375:in `return_or_raise'
2015-03-30 15:36:45 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.63.0/lib/aws/core/client.rb:476:in `client_request'
2015-03-30 15:36:45 +0900 [error]: (eval):3:in `get_bucket_versioning'
2015-03-30 15:36:45 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.63.0/lib/aws/s3/bucket.rb:456:in `versioning_state'
2015-03-30 15:36:45 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.63.0/lib/aws/s3/bucket.rb:444:in `versioning_enabled?'
2015-03-30 15:36:45 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.63.0/lib/aws/s3/bucket.rb:507:in `exists?'
2015-03-30 15:36:45 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-s3-0.5.6/lib/fluent/plugin/out_s3.rb:139:in `ensure_bucket'
2015-03-30 15:36:45 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-s3-0.5.6/lib/fluent/plugin/out_s3.rb:96:in `start'

I think, We need to specify "s3_endpoint" configuration to aws-sdk instead of "endpoint" when we use S3 compatible service.
I changed the line 79 of out_s3.rb below, and then, I solved this error message.  

#options[:endpoint] = @s3_endpoint if @s3_endpoint
options[:s3_endpoint] = @s3_endpoint if @s3_endpoint

Thanks.

**Comment by repeatedly** [comment]
Hmm... maybe aws-sdk-ruby removes `endpoint` parameter from core configuration.
I will fix this later.

**Comment by repeatedly** [comment]
@yhidai Could you also check this patch? https://github.com/fluent/fluent-plugin-s3/pull/76

**Comment by yhidai** [comment]
Thank you for your quick response.
I tried patch#76, and I could solve this issue.
Thanks!

**Comment by afeld** [comment]
[The docs](https://docs.fluentd.org/v1.0/articles/out_s3#s3_endpoint) now say "This option is deprecated"... I guess this support is going away?

**Comment by repeatedly** [comment]
You can still use this parameter for S3 compatible service.
For S3, this parameter is deprecated.
